// GENERATED by `scripts/android/gen-enrichment-prompt.py` from
// `FutureVoice/Services/DrillEnrichmentEngine.swift`. Do not edit by hand —
// edit the Swift source and re-run, or the two platforms start teaching the
// same card differently.

export function systemPrompt(
  languageName: string,
  nativeName: string,
  contract: string,
): string {
  return `${contract}
The user is studying a flashcard for ${languageName} fluency. The
card has a target phrase (the natural version) and optionally a source
phrase (what they originally said) + reason. Generate a rich
enrichment payload so they really internalize the pattern instead of
memorizing one swap.

Use the user's persona to GROUND examples in situations they actually
live in (their city, work, household, interests). Generic textbook
scenarios are wrong here.

Return STRICT JSON only — no prose, no code fences:
{
  "examples": [
    { "situation": "...", "sentence": "..." },
    { "situation": "...", "sentence": "..." },
    { "situation": "...", "sentence": "..." }
  ],
  "variants": [
    { "phrase": "...", "note": "..." },
    { "phrase": "...", "note": "..." }
  ],
  "memory_hook": "..."
}

Rules:
- examples: 3 short scenarios in DIFFERENT contexts from the persona's
  life, each with one line that uses the target phrase naturally.
  situation = brief frame in ${nativeName} (≤ 14 words). sentence = the
  spoken line in ${languageName}.
- variants: 2-3 alternate ways to express the same intent at similar
  fluency level. phrase = ${languageName}. note = ≤ 14 words in
  ${nativeName} on when this variant fits better (register, formality,
  mood).
- memory_hook: ONE sentence in ${nativeName} — a sensory, situational,
  or relatable trigger that makes the phrase easy to recall later. NOT
  "remember this!" — something concrete like "When you're about to
  apologize but it's not really your fault, reach for this."
- So: "sentence" and "phrase" in ${languageName} (the learner speaks
  them); "situation", "note" and "memory_hook" in ${nativeName} (the
  learner reads them to understand). A ${languageName} phrase quoted
  inside a ${nativeName} line stays untranslated.`
}
