#!/usr/bin/env python3
"""Lift the voice-accent catalog out of the Swift source into Kotlin.

The accent PROMPTS are sent upstream as `voice_description` and the sample
TEXT is what the previews speak — both are content, and content that is
retyped drifts. Two platforms would then remix the same clone with different
instructions, and the difference shows up as a voice that doesn't sound like
the same person on one of them.

Run after touching VoiceAccentCatalog:

    python3 scripts/android/gen-voice-accents.py
"""
import os
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parents[2]
# VOICE_ACCENT_SWIFT points at another checkout's copy (the iOS working tree)
# when feat/android's own copy of the Swift file is behind.
SRC = pathlib.Path(os.environ.get("VOICE_ACCENT_SWIFT") or ROOT / "FutureVoice/Services/VoiceAccent.swift")
OUT = ROOT / "android/app/src/main/java/com/roro/futurevoice/data/VoiceAccent.kt"

src = SRC.read_text()


def swift_concat(text: str) -> str:
    """Join a Swift `"a" + "b"` string expression into one literal."""
    parts = re.findall(r'"((?:[^"\\]|\\.)*)"', text)
    if not parts:
        sys.exit(f"no string literal in: {text[:80]}")
    return "".join(parts)


# The shared prompt shape, with its one interpolation left as a placeholder.
m = re.search(r'private static func prompt\(_ accent: String\) -> String \{(.*?)\n    \}', src, re.S)
if not m:
    sys.exit("could not find prompt(_:)")
shape = swift_concat(m.group(1))
if r"\(accent)" not in shape:
    sys.exit("prompt shape no longer interpolates `accent`; port it by hand")
shape = shape.replace(r"\(accent)", "%s")

# The per-language options.
m = re.search(r'byLanguage: \[String: \[VoiceAccent\]\] = \[(.*?)\n    \]', src, re.S)
if not m:
    sys.exit("could not find byLanguage")
options = []
for lang_block in re.finditer(r'"(\w+)": \[(.*?)\n        \]', m.group(1), re.S):
    lang = lang_block.group(1)
    for opt in re.finditer(
        r'VoiceAccent\(id: "([^"]+)", label: "([^"]+)",\s*prompt: prompt\("([^"]+)"\)\)',
        lang_block.group(2),
    ):
        options.append((lang, opt.group(1), opt.group(2), opt.group(3)))
if not options:
    sys.exit("no accent options parsed — the literal's shape changed")

# The sample lines.
m = re.search(r'samples: \[String: String\] = \[(.*?)\n    \]', src, re.S)
if not m:
    sys.exit("could not find samples")
samples = []
for s in re.finditer(r'"(\w+)": ((?:\s*\+?\s*"(?:[^"\\]|\\.)*")+)', m.group(1)):
    samples.append((s.group(1), swift_concat(s.group(2))))

rows = "\n".join(
    f'        VoiceAccent("{lang}", "{i}", "{label}", prompt("{acc}")),'
    for lang, i, label, acc in options
)
sample_rows = "\n".join(f'        "{lang}" to "{text}",' for lang, text in samples)

m_strength = re.search(r"static let promptStrength: Double = ([0-9.]+)", src)
if not m_strength:
    sys.exit("VoiceAccent.swift has no promptStrength")
strength = m_strength.group(1)
OUT.write_text(f'''package com.roro.futurevoice.data

// GENERATED by scripts/android/gen-voice-accents.py — do not edit.
// Source: FutureVoice/Services/VoiceAccent.swift

/**
 * A selectable output accent for the cloned voice, applied AFTER cloning via
 * ElevenLabs voice remixing (`elevenlabs-voice-remix`).
 *
 * Exists because a clone recorded in the learner's NATIVE language carries no
 * target-language accent information at all — the TTS model fills that gap
 * with its own default (US English for `en`), which is wrong for, say, a
 * learner living in London. Remixing keeps the person and changes only the
 * accent; the learner auditions a few takes and keeps one.
 */
data class VoiceAccent(
    /** Target language this option belongs to. */
    val language: String,
    /** Stable id, reported to analytics ("en-GB"). */
    val id: String,
    /** Row label. */
    val label: String,
    /** The remix instruction sent upstream as `voice_description`. */
    val prompt: String,
)

object VoiceAccentCatalog {{

    /**
     * One shared shape so every option pulls equally hard toward "same
     * person, different accent" — the remix must never drift into a new
     * character, because speaker similarity is the product.
     */
    /**
     * How far the remix may drift from the reference audio (upstream
     * `prompt_strength`: 0 keeps almost everything of the recording, 1 keeps
     * almost nothing). The prompt ASKS for the same person; this is what
     * decides it. Low on purpose: an accent that sounds like someone else is
     * worse than no accent. Chosen by ear with
     * `scripts/voice-remix-probe.sh` — retune there, never by feel.
     */
    const val PROMPT_STRENGTH: Double = {strength}

    private fun prompt(accent: String) = "{shape}".format(accent)

    private val all = listOf(
{rows}
    )

    /** Accent choices for a target language. Empty = the picker never shows
     *  for that language; v1 ships English only. */
    fun options(language: String): List<VoiceAccent> =
        all.filter {{ it.language == language.take(2) }}

    /**
     * The accent every new clone is remixed into — the FIRST option of the
     * language (iOS `VoiceAccentCatalog.defaultAccent(for:)`, 2026-10-08).
     * Null = no remix for this language.
     */
    fun defaultAccent(language: String): VoiceAccent? = options(language).firstOrNull()

    private val samples = mapOf(
{sample_rows}
    )

    /**
     * The line the remix previews speak (ElevenLabs wants 100–1000 chars).
     * Written to surface accent-revealing sounds — for English: t-flapping
     * ("water", "better"), the bath/trap split ("can't", "half past"),
     * rhoticity ("park", "there"), and a tag question's intonation.
     */
    fun sampleText(language: String): String =
        samples[language.take(2)] ?: samples["en"]!!
}}
''')
print(f"wrote {OUT.relative_to(ROOT)} — {len(options)} accents, {len(samples)} samples")
