#!/usr/bin/env python3
"""Lift FreeTalkOpeners' bundled lines and pool prompt out of the Swift source.

Three pieces of CONTENT: the per-language INTRO line (the very first free talk,
before the fluent self has met the learner), the per-language FALLBACK line
(spoken while no pool exists yet), and the prompt that writes a learner's pool
of six rotating greetings. Retyped, the two platforms greet the same learner
differently — and the intro line is the first thing the product ever says.

    python3 scripts/android/gen-free-talk-openers.py
"""
import pathlib, re, sys

ROOT = pathlib.Path(__file__).resolve().parents[2]
SRC = ROOT / "FutureVoice/Services/FreeTalkOpeners.swift"
OUT = ROOT / "android/app/src/main/java/com/roro/futurevoice/talk/FreeTalkOpenerContent.kt"
src = SRC.read_text()

def table(name):
    m = re.search(rf'private static let {name}: \[String: String\] = \[(.*?)\n\s*\]', src, re.S)
    if not m: sys.exit(f"no table {name}")
    pairs = re.findall(r'"(\w+)":\s*"((?:[^"\\]|\\.)*)"', m.group(1))
    if not pairs: sys.exit(f"empty table {name}")
    return pairs

intro = table("introOpeners")
fallback = table("fallbackOpeners")

m = re.search(r'let name = .*?\n\s*let languageName = .*?\n\s*return """\n(.*?)\n\s*"""', src, re.S)
if not m: sys.exit("no pool prompt literal")
lines = m.group(1).split("\n")
indent = min((len(l) - len(l.lstrip()) for l in lines if l.strip()), default=0)
prompt = "\n".join(l[indent:] if l.strip() else "" for l in lines)
for k, v in {r"\(languageName)": "$languageName",
             r"\(proficiency.rawValue.uppercased())": "$levelCode",
             r"\(name)": "$name"}.items():
    prompt = prompt.replace(k, v)
if r"\(" in prompt: sys.exit("unmapped interpolation: " + re.search(r"\\\([^)]*\)", prompt).group(0))
if "$" in re.sub(r"\$(languageName|levelCode|name)\b", "", prompt): sys.exit("literal $ in prompt")

def kmap(pairs):
    return ",\n".join(f'        "{k}" to "{v}"' for k, v in pairs)

OUT.write_text(f'''package com.roro.futurevoice.talk

// GENERATED by scripts/android/gen-free-talk-openers.py — do not edit.
// Source: FutureVoice/Services/FreeTalkOpeners.swift

/** Bundled greeting lines and the pool prompt, lifted from the iOS source. */
object FreeTalkOpenerContent {{
    /** The very first free talk, before the fluent self has met the learner
     *  (`UserPersona.metAt == null`). It introduces ITSELF first. */
    val intro: Map<String, String> = mapOf(
{kmap(intro)}
    )

    /** What a free talk opens on while no pool exists yet. */
    val fallback: Map<String, String> = mapOf(
{kmap(fallback)}
    )

    fun poolPrompt(languageName: String, levelCode: String, name: String): String =
        """{prompt}""".trimIndent()
}}
''')
print(f"wrote {OUT.relative_to(ROOT)} — intro {len(intro)}, fallback {len(fallback)}")
