#!/usr/bin/env python3
"""Extract WatchTab's `situationTree` into Kotlin.

The tree is CONTENT — the categories a learner drills into on Watch, and the
ready-to-edit situation text at each leaf. Retyping it by hand is how the two
platforms would drift into offering different situations, so it is read out of
the Swift source instead. Re-run after editing `WatchTab.swift`.

    python3 scripts/android/gen-situation-tree.py
"""
import pathlib
import re

ROOT = pathlib.Path(__file__).resolve().parents[2]
SRC = ROOT / "FutureVoice/Views/WatchTab.swift"
OUT = (ROOT / "android/app/src/main/java/com/roro/futurevoice/data"
            / "SituationTree.kt")

BLOCK = re.compile(r"static let situationTree: \[SituationBranch\] = \[(.*?)\n    \]",
                   re.S)


def swift_string(raw: str) -> str:
    """Swift literal → Kotlin literal. Both use \\" and \\\\; $ needs escaping."""
    return raw.replace("$", "\\$")


def logical_lines(body: str):
    """One line per `SituationBranch(` call.

    The Swift literal wraps a long `situation:` onto its own continuation
    line, so a raw line scan sees the leaf without its text. Anything that
    isn't the start of a new call belongs to the call above it.
    """
    out = []
    for line in body.splitlines():
        if "SituationBranch(" in line or not out:
            out.append(line.rstrip())
        else:
            out[-1] = out[-1].rstrip() + " " + line.strip()
    return out


def parse(body: str):
    """Walk the literal, tracking indent to rebuild the nesting."""
    roots = []
    stack = [(-1, roots)]          # (indent, sibling list)
    for line in logical_lines(body):
        if "SituationBranch(" not in line:
            continue
        indent = len(line) - len(line.lstrip())
        label = re.search(r'label: "((?:[^"\\]|\\.)*)"', line)
        if not label:
            continue
        icon = re.search(r'icon: "((?:[^"\\]|\\.)*)"', line)
        situation = re.search(r'situation: "((?:[^"\\]|\\.)*)"', line)
        node = {
            "label": label.group(1),
            "icon": icon.group(1) if icon else None,
            "situation": situation.group(1) if situation else None,
            "children": [],
        }
        while stack and indent <= stack[-1][0]:
            stack.pop()
        stack[-1][1].append(node)
        if "children: [" in line:
            stack.append((indent, node["children"]))
    return roots


def render(nodes, indent: int) -> str:
    pad = " " * indent
    out = []
    for n in nodes:
        parts = [f'label = "{swift_string(n["label"])}"']
        if n["icon"]:
            parts.append(f'icon = "{n["icon"]}"')
        if n["situation"]:
            parts.append(f'situation = "{swift_string(n["situation"])}"')
        if n["children"]:
            kids = render(n["children"], indent + 8)
            parts.append(f"children = listOf(\n{kids}\n{pad}    )")
        out.append(f"{pad}Branch(\n{pad}    " + f",\n{pad}    ".join(parts) + f",\n{pad})")
    return ",\n".join(out)


def main() -> None:
    m = BLOCK.search(SRC.read_text())
    if not m:
        raise SystemExit("situationTree not found in WatchTab.swift")
    tree = parse(m.group(1))
    if not tree:
        raise SystemExit("parsed an empty tree — the Swift literal's shape changed")
    leaves = sum(1 for r in tree for c in r["children"] for _ in c["children"])
    OUT.write_text(f'''package com.roro.futurevoice.data

/**
 * "Likely situations" — the category chain a learner drills into on Watch
 * (cafe → ordering → order came out wrong), whose leaves prefill the
 * composer, always editable.
 *
 * GENERATED by `scripts/android/gen-situation-tree.py` from
 * `FutureVoice/Views/WatchTab.swift`. This is CONTENT, not code: edit the
 * Swift source and re-run, or the two platforms start offering different
 * situations. {len(tree)} categories, {leaves} leaves.
 */
object SituationTree {{

    data class Branch(
        val label: String,
        /** SF Symbol name; only meaningful on a top-level entry. */
        val icon: String? = null,
        val children: List<Branch> = emptyList(),
        /** Set on leaves: the assembled, ready-to-edit situation. */
        val situation: String? = null,
    )

    val roots: List<Branch> = listOf(
{render(tree, 8)},
    )

    /**
     * Categories matching the persona's "when do you most need it" picks
     * first, tree order within each group. The onboarding chips are the whole
     * point of asking — this is where they visibly pay off.
     */
    fun prioritized(situations: List<String>): List<Branch> {{
        if (situations.isEmpty()) return roots
        val wanted = situations.flatMap {{ labels(it) }}.toSet()
        if (wanted.isEmpty()) return roots
        return roots.filter {{ it.label in wanted }} + roots.filterNot {{ it.label in wanted }}
    }}

    /**
     * One persona situation → category labels. Presets map explicitly; free
     * text matches a category when its label appears in what they wrote.
     */
    private fun labels(situation: String): List<String> {{
        PRESETS[situation]?.let {{ return it }}
        val lowered = situation.lowercase()
        return roots.map {{ it.label }}.filter {{ lowered.contains(it.lowercase()) }}
    }}

    private val PRESETS = mapOf(
        "Work meetings" to listOf("Work"),
        "Client calls" to listOf("Work"),
        "Doctor / clinic" to listOf("Health"),
        "Travel" to listOf("Travel"),
        "Online shopping" to listOf("Shopping"),
        "Customer service" to listOf("Shopping"),
        "Daily small talk" to listOf("Cafe"),
    )
}}
''')
    print(f"wrote {OUT.relative_to(ROOT)} — {len(tree)} categories, {leaves} leaves")


if __name__ == "__main__":
    main()
