#!/usr/bin/env python3
"""Lift the spoken-text rules out of `CoachingLanguage.swift`.

`breathPunctuation` keeps a synthesized line from being read without
breathing, and is spliced into every prompt whose text is SPOKEN — the call,
the scene, the openers, the voicemail. `selfWarmth` says what "warm" means
for the fluent self (interest, never longing — iOS `a212c70`). Retyped, the
two platforms would drift, so both are extracted.

    python3 scripts/android/gen-breath-punctuation.py            # worktree Swift
    python3 scripts/android/gen-breath-punctuation.py --ref 7c12b9e   # iOS at a commit
"""
import pathlib
import re
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parents[2]
REL = "FutureVoice/Services/CoachingLanguage.swift"
OUT = ROOT / "android/app/src/main/java/com/roro/futurevoice/talk/CoachingLanguage.kt"

ref = None
if "--ref" in sys.argv:
    ref = sys.argv[sys.argv.index("--ref") + 1]
source = (subprocess.check_output(["git", "-C", str(ROOT), "show", f"{ref}:{REL}"], text=True)
          if ref else (ROOT / REL).read_text())


def literal(name: str) -> str:
    m = re.search(rf'static let {name} = """\n(.*?)\n\s*"""', source, re.S)
    if not m:
        sys.exit(f"no {name} literal")
    # The Swift literal uses `\` line continuations: those lines join with a
    # single space, the rest keep their newline.
    text = ""
    for line in (l.strip() for l in m.group(1).split("\n")):
        text += (line[:-1].rstrip() + " ") if line.endswith("\\") else (line + "\n")
    text = text.strip()
    if '"""' in text or "$" in text:
        sys.exit(f"{name} carries a sequence a Kotlin raw string can't hold")
    return text


breath = literal("breathPunctuation")
warmth = literal("selfWarmth")

OUT.write_text(f'''package com.roro.futurevoice.talk

// GENERATED by scripts/android/gen-breath-punctuation.py — do not edit.
// Source: FutureVoice/Services/CoachingLanguage.swift (breathPunctuation, selfWarmth).

/**
 * The shared rules for text that will be SPOKEN. The synthesizer pauses at
 * punctuation and nowhere else, so a line with none is read without
 * breathing — measured on both TTS models and on the gateway's per-sentence
 * path. Spliced into every prompt whose output is read aloud.
 */
object CoachingLanguage {{
    const val breathPunctuation = """{breath}"""

    /**
     * What "warm" means for the fluent self: interest in their day, never
     * longing ("보고 싶어"). The caller IS the learner; nobody misses
     * themselves. Only where the model speaks AS the fluent self — a cast
     * partner may well say it.
     */
    const val selfWarmth = """{warmth}"""
}}
''')
print(f"wrote {OUT.relative_to(ROOT)} ({len(breath)} + {len(warmth)} chars)")
