#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Extract DrillEnrichmentEngine's system prompt into the edge function.

The prompt decides what a learner is TOLD about a card — the examples, the
variants, the memory hook — so retyping it is how the two platforms start
teaching the same card differently. It is read out of the Swift source and
written into `supabase/functions/drill-enrichment/prompt.ts`.

iOS still builds it client-side and calls `gemini`; nothing here switches it.

    python3 scripts/android/gen-enrichment-prompt.py
"""
import pathlib
import re

ROOT = pathlib.Path(__file__).resolve().parents[2]
SRC = ROOT / "FutureVoice/Services/DrillEnrichmentEngine.swift"
OUT = ROOT / "supabase/functions/drill-enrichment/prompt.ts"

BLOCK = re.compile(r'nativeLanguage: String\) -> String \{.*?return """\n(.*?)\n        """',
                   re.S)


def dedent(body: str) -> str:
    lines = body.split("\n")
    indents = [len(l) - len(l.lstrip()) for l in lines if l.strip()]
    cut = min(indents) if indents else 0
    return "\n".join(l[cut:] if len(l) >= cut else l.lstrip() for l in lines)


def join_continuations(body: str) -> str:
    return re.sub(r"\\\n\s*", " ", body)


def to_ts(body: str) -> str:
    known = {
        r"\(languageName)": "${languageName}",
        r"\(nativeName)": "${nativeName}",
        r"\(CoachingLanguage.contract(target: targetLanguage, native: nativeLanguage))":
            "${contract}",
    }
    for swift, ts in known.items():
        body = body.replace(swift, ts)
    leftover = re.findall(r"\\\([^)]*\)", body)
    if leftover:
        raise SystemExit(f"unhandled Swift interpolation: {sorted(set(leftover))}")
    body = body.replace("\\", "\\\\").replace("`", "\\`")
    return body.replace("\\${", "${")


def main() -> None:
    m = BLOCK.search(SRC.read_text())
    if not m:
        raise SystemExit("systemPrompt literal not found in DrillEnrichmentEngine.swift")
    body = to_ts(dedent(join_continuations(m.group(1))))
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(f'''// GENERATED by `scripts/android/gen-enrichment-prompt.py` from
// `FutureVoice/Services/DrillEnrichmentEngine.swift`. Do not edit by hand —
// edit the Swift source and re-run, or the two platforms start teaching the
// same card differently.

export function systemPrompt(
  languageName: string,
  nativeName: string,
  contract: string,
): string {{
  return `{body}`
}}
''')
    print(f"wrote {OUT.relative_to(ROOT)} — {len(body)} chars")


if __name__ == "__main__":
    main()
