#!/usr/bin/env python3
"""Lift TopicEngine.counterpartSystemPrompt and the counterpart half of
FallbackText out of the Swift source.

The ideas on a person's card are MATERIAL — the blurb becomes the scene the
learner talks through — so both platforms must ask for them in the same
words. Extracted, never retyped.

    python3 scripts/android/gen-counterpart-ideas.py
"""
import pathlib, re, sys
ROOT = pathlib.Path(__file__).resolve().parents[2]
SWIFT = ROOT / "FutureVoice/Services/TopicEngine.swift"
OUT = ROOT / "android/app/src/main/java/com/roro/futurevoice/talk/CounterpartIdeasContent.kt"
src = SWIFT.read_text()
m = re.search(r'static func counterpartSystemPrompt\(.*?return """\n(.*?)\n\s*"""', src, re.S)
if not m: sys.exit("no counterpartSystemPrompt literal")
lines = m.group(1).split("\n")
indent = min((len(l) - len(l.lstrip()) for l in lines if l.strip()), default=0)
text = "\n".join(l[indent:] if l.strip() else "" for l in lines)
text = text.replace(r"\(count)", "$count").replace(r"\(languageName)", "$languageName")
if r"\(" in text: sys.exit("unmapped interpolation: " + re.search(r"\\\([^)]*\)", text).group(0))
if "$" in re.sub(r"\$(count|languageName)\b", "", text): sys.exit("literal $ in prompt")
# Fallback rows: "xx": FallbackText( ... catchUpWithFormat: "...", catchUpBlurb: "...", onYourMind: "...", onYourMindBlurb: "...")
rows = []
for lang, body in re.findall(r'"([a-z]{2})": FallbackText\((.*?)\),\n', src, re.S):
    f = {}
    for k in ("catchUpWithFormat", "catchUpBlurb", "onYourMind", "onYourMindBlurb"):
        mm = re.search(k + r': "((?:[^"\\]|\\.)*)"', body)
        if not mm: sys.exit(f"{lang}: missing {k}")
        f[k] = mm.group(1).replace("%@", "%s")
    rows.append((lang, f))
if not rows: sys.exit("no FallbackText rows")
def q(s): return '"' + s.replace("\\", "\\\\").replace('"', '\\"').replace("$", "\\$") + '"'
kt_rows = ",\n".join(f'        "{l}" to Fallback({q(f["catchUpWithFormat"])}, {q(f["catchUpBlurb"])}, {q(f["onYourMind"])}, {q(f["onYourMindBlurb"])})' for l, f in rows)
OUT.write_text(f'''package com.roro.futurevoice.talk

// GENERATED by scripts/android/gen-counterpart-ideas.py — do not edit.
// Source: FutureVoice/Services/TopicEngine.swift (counterpartSystemPrompt, FallbackText).

object CounterpartIdeasContent {{
    fun systemPrompt(languageName: String, count: Int): String = """{text}""".trimIndent()

    class Fallback(val catchUpWithFormat: String, val catchUpBlurb: String, val onYourMind: String, val onYourMindBlurb: String)

    private val fallbacks = mapOf(
{kt_rows},
    )

    fun fallback(languageCode: String): Fallback = fallbacks[languageCode] ?: fallbacks.getValue("en")
}}
''')
print(f"wrote {OUT.relative_to(ROOT)} ({len(rows)} fallback languages)")
