#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Extract WeeklyReportEngine's system prompt into the edge function.

The prompt is the PRODUCT — the rules by which a learner's level is judged —
and it is far too long and too load-bearing to retype. It is read out of the
Swift source and written into `supabase/functions/weekly-report/prompt.ts`,
so the two can only differ by someone editing the generated file, which the
banner tells them not to do.

iOS still builds it client-side and calls `gemini`; nothing here switches it.
Re-run after editing `WeeklyReportEngine.swift`.

    python3 scripts/android/gen-weekly-prompt.py
"""
import pathlib
import re

ROOT = pathlib.Path(__file__).resolve().parents[2]
SRC = ROOT / "FutureVoice/Services/WeeklyReportEngine.swift"
OUT = ROOT / "supabase/functions/weekly-report/prompt.ts"

# The multi-line Swift string literal inside `systemPrompt`, up to the closing
# delimiter that ends the `var s = """ … """` assignment.
BLOCK = re.compile(r'var s = """\n(.*?)\n        """', re.S)


def dedent(body: str) -> str:
    """Swift strips the closing delimiter's indentation from a multi-line
    literal. The extract keeps it, so it is removed here — otherwise every
    line of the prompt ships with eight leading spaces the model reads past.
    """
    lines = body.split("\n")
    indents = [len(l) - len(l.lstrip()) for l in lines if l.strip()]
    cut = min(indents) if indents else 0
    return "\n".join(l[cut:] if len(l) >= cut else l.lstrip() for l in lines)


def join_continuations(body: str) -> str:
    """A trailing backslash inside a Swift multi-line literal joins the next
    line. Left alone it becomes a literal backslash in the TS template —
    visible to the model, in the middle of a sentence.
    """
    return re.sub(r"\\\n\s*", " ", body)


def to_ts(body: str) -> str:
    """Swift interpolation → TS template placeholders.

    Only four names are interpolated, and each maps to a parameter of the
    generated builder. Anything else interpolated is a change the generator
    has not been taught, so it fails loudly rather than shipping a literal
    `\\(something)` into a prompt.
    """
    known = {
        r"\(targetName)": "${targetName}",
        r"\(nativeName)": "${nativeName}",
        r"\(CoachingLanguage.contract(target: targetLanguage, native: nativeLanguage))":
            "${contract}",
    }
    for swift, ts in known.items():
        body = body.replace(swift, ts)
    leftover = re.findall(r"\\\([^)]*\)", body)
    if leftover:
        raise SystemExit(f"unhandled Swift interpolation: {sorted(set(leftover))}")
    # Escape what a TS template literal treats specially. Backslashes first.
    body = body.replace("\\", "\\\\").replace("`", "\\`")
    # Restore the placeholders the escape pass just broke.
    return body.replace("\\${", "${")


def main() -> None:
    m = BLOCK.search(SRC.read_text())
    if not m:
        raise SystemExit("systemPrompt literal not found in WeeklyReportEngine.swift")
    body = to_ts(dedent(join_continuations(m.group(1))))
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(f'''// GENERATED by `scripts/android/gen-weekly-prompt.py` from
// `FutureVoice/Services/WeeklyReportEngine.swift`. Do not edit by hand —
// edit the Swift source and re-run, or the two platforms start judging the
// same learner by different rules.
//
// This is the PRODUCT: the rules a learner's level is assessed by. Every
// clause in it was argued for once, so nothing here is decoration.

export function systemPrompt(
  targetName: string,
  nativeName: string,
  contract: string,
  previousSummary?: string | null,
): string {{
  let s = `{body}`
  if (previousSummary) {{
    s += `\\n\\nPrevious report summary (for trend comparison):\\n${{previousSummary}}`
  }}
  return s
}}
''')
    print(f"wrote {OUT.relative_to(ROOT)} — {len(body)} chars")


if __name__ == "__main__":
    main()
