#!/usr/bin/env python3
"""Lift coach mode's prompt text out of the Swift source at a ref.

Three literals, byte for byte (iOS 1.1.4 `6e9eb92` + `eaaf3af` + `5b0587a`):
  - `CoachSuggester.system` — the "try saying" writer's instructions;
  - `ConversationEngine.speechScale(for:).vocabulary`, the three bands it
    splices in (Android has no other use for the scale yet);
  - `ConversationEngine.beginnerQuestions` — the A1/A2 question rules
    appended to the conversation prompt.
Retyped, iOS and Android would coach the same learner differently.

    python3 scripts/android/gen-coach-prompts.py --ref ebf848e
"""
import argparse, json, pathlib, re, subprocess, sys

ROOT = pathlib.Path(__file__).resolve().parents[2]
OUT = ROOT / "android/app/src/main/java/com/roro/futurevoice/talk/CoachPrompts.kt"

ap = argparse.ArgumentParser()
ap.add_argument("--ref", default="ebf848e")
args = ap.parse_args()


def show(path):
    return subprocess.run(["git", "-C", str(ROOT), "show", f"{args.ref}:{path}"],
                          check=True, capture_output=True, text=True).stdout


def literal_after(src, anchor, start=0):
    """The Swift multiline literal that opens on the first `\"\"\"` after
    `anchor`, as (segments, end). Segments are ('t', text) or ('i', expr)."""
    i = src.find(anchor, start)
    if i < 0: sys.exit(f"anchor not found: {anchor!r}")
    o = src.find('"""', i)
    body_start = src.find("\n", o) + 1
    close = re.compile(r'\n([ \t]*)"""').search(src, body_start - 1)
    raw = src[body_start:close.start() + 1]
    indent = close.group(1)
    lines = raw.split("\n")[:-1]
    out = []
    for ln in lines:
        if ln.strip() == "": out.append("")
        elif ln.startswith(indent): out.append(ln[len(indent):])
        else: sys.exit(f"bad indent: {ln!r}")
    text = ""
    for n, ln in enumerate(out):
        last = n == len(out) - 1
        if ln.endswith("\\") and not ln.endswith("\\\\"):
            text += ln[:-1]
        else:
            text += ln + ("" if last else "\n")
    # Escapes and interpolations.
    segs, buf, k = [], "", 0
    while k < len(text):
        c = text[k]
        if c == "\\":
            nxt = text[k + 1]
            if nxt == "(":
                depth, j = 1, k + 2
                while depth:
                    if text[j] == "(": depth += 1
                    elif text[j] == ")": depth -= 1
                    j += 1
                if buf: segs.append(("t", buf)); buf = ""
                segs.append(("i", text[k + 2:j - 1]))
                k = j
                continue
            buf += {"\"": "\"", "\\": "\\", "n": "\n", "t": "\t"}[nxt]
            k += 2
            continue
        buf += c
        k += 1
    if buf: segs.append(("t", buf))
    return segs, close.end()


def kotlin(segs, interp):
    parts = []
    for kind, v in segs:
        if kind == "t":
            parts.append(json.dumps(v, ensure_ascii=False).replace("$", "\\$"))
        else:
            if v not in interp: sys.exit(f"unmapped interpolation: {v}")
            parts.append(interp[v])
    return " +\n        ".join(parts)


engine = show("FutureVoice/Services/ConversationEngine.swift")
coach = show("FutureVoice/Services/CoachMode.swift")

# speechScale: three `vocabulary: """` literals, in band order.
fn = engine.find("static func speechScale(for level: CEFRLevel)")
vocab, pos = [], fn
for _ in range(3):
    segs, pos = literal_after(engine, "vocabulary: \"\"\"", pos)
    vocab.append(kotlin(segs, {}))

beg_segs, _ = literal_after(engine, "static func beginnerQuestions(_ level: CEFRLevel)")
beginner = kotlin(beg_segs, {"level.rawValue.uppercased()": "level.code.uppercase()"})

sys_segs, _ = literal_after(coach, "private static func system(target: String, native: String, level: CEFRLevel)")
suggester = kotlin(sys_segs, {
    "level.rawValue.uppercased()": "level.code.uppercase()",
    "targetName": "targetName",
    "nativeName": "nativeName",
    "scale.vocabulary": "speechVocabulary(level)",
})

OUT.write_text(f'''package com.roro.futurevoice.talk

import com.roro.futurevoice.data.CefrLevel

// GENERATED by scripts/android/gen-coach-prompts.py --ref {args.ref} — do not edit.
// Source: FutureVoice/Services/ConversationEngine.swift (speechScale vocabulary,
// beginnerQuestions) and FutureVoice/Services/CoachMode.swift (CoachSuggester.system).

object CoachPrompts {{
    /** iOS `ConversationEngine.speechScale(for:).vocabulary`. */
    fun speechVocabulary(level: CefrLevel): String = when (level) {{
        CefrLevel.A1, CefrLevel.A2 ->
        {vocab[0]}
        CefrLevel.B1, CefrLevel.B2 ->
        {vocab[1]}
        CefrLevel.C1, CefrLevel.C2 ->
        {vocab[2]}
    }}

    /**
     * iOS `ConversationEngine.beginnerQuestions`: how the fluent self ASKS an
     * A1/A2 learner. Empty at B1 and above, so those prompts stay byte for
     * byte what they were.
     */
    fun beginnerQuestions(level: CefrLevel): String {{
        if (level != CefrLevel.A1 && level != CefrLevel.A2) return ""
        return {beginner}
    }}

    /** iOS `CoachSuggester.system(target:native:level:)`. */
    fun suggesterSystem(targetName: String, nativeName: String, level: CefrLevel): String =
        {suggester}
}}
''')
print(f"wrote {OUT.relative_to(ROOT)}")
