#!/usr/bin/env python3
"""Lift ConversationEngine.correctionOnlyPrompt out of the Swift source.

On the realtime call path the reply is prose and the correction is a
SEPARATE, later request — this is the prompt for that request. It is
content: retyped, the two platforms would judge the same spoken line by
different rules, and the ASR guards (drop / digit / contraction) are exactly
the lines a retype loses. So it is extracted, never copied by hand.

    python3 scripts/android/gen-correction-prompt.py

Fails loudly on any interpolation it does not know how to map.
"""
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parents[2]
SWIFT = ROOT / "FutureVoice/Services/ConversationEngine.swift"
OUT = ROOT / "android/app/src/main/java/com/roro/futurevoice/talk/CorrectionOnlyPrompt.kt"

src = SWIFT.read_text()
m = re.search(
    r'static func correctionOnlyPrompt\(.*?\{\s*'
    r'let targetName = .*?\n\s*let nativeName = .*?\n\s*return """\n(.*?)\n\s*"""',
    src, re.S)
if not m:
    sys.exit("could not find correctionOnlyPrompt's literal")

body = m.group(1)
lines = body.split("\n")
indent = min((len(l) - len(l.lstrip()) for l in lines if l.strip()), default=0)
text = "\n".join(l[indent:] if l.strip() else "" for l in lines)

# The three interpolations the Swift literal uses, mapped to Kotlin
# template names. Anything else is an unmapped interpolation → fail.
mapping = {
    r"\(targetName)": "$targetName",
    r"\(nativeName)": "$nativeName",
    r"\(level.rawValue)": "$levelCode",
}
for k, v in mapping.items():
    text = text.replace(k, v)
if r"\(" in text:
    sys.exit("prompt carries an interpolation this script doesn't map: "
             + re.search(r"\\\([^)]*\)", text).group(0))

# Kotlin raw strings can't escape `$`; only our own placeholders may remain.
stray = re.sub(r"\$(targetName|nativeName|levelCode)\b", "", text)
if "$" in stray:
    sys.exit("prompt carries a literal '$' — escape it before generating")

OUT.write_text(f'''package com.roro.futurevoice.talk

// GENERATED by scripts/android/gen-correction-prompt.py — do not edit.
// Source: FutureVoice/Services/ConversationEngine.swift (correctionOnlyPrompt).

import com.roro.futurevoice.data.CefrLevel
import com.roro.futurevoice.data.LanguageCatalog

/**
 * The correction request on the realtime path. The reply is prose and the
 * voice is already playing by the time this fires — nothing the learner hears
 * ever waits on coaching. Extracted from the Swift source so both platforms
 * judge a spoken line by the same rules, ASR guards included.
 */
object CorrectionOnlyPrompt {{
    fun build(targetLanguage: String, nativeLanguage: String, level: CefrLevel): String {{
        val targetName = LanguageCatalog.englishName(targetLanguage)
        val nativeName = LanguageCatalog.englishName(nativeLanguage)
        val levelCode = level.code.uppercase()
        return """{text}""".trimIndent()
    }}
}}
''')
print(f"wrote {OUT.relative_to(ROOT)} ({len(text)} chars)")
