#!/usr/bin/env python3
"""Lift the scenario composer's drill-down CONTENT out of the Swift source:
`TopicEngine.pathSystemPrompt`, its shipped sub-area seeds, and the composer's
preset categories.

Chips are material — the blurb becomes the scenario the learner talks
through — so the two platforms must offer the same buckets and ask for the
specifics in the same words. Extracted, never retyped.

    python3 scripts/android/gen-path-ideas.py
"""
import pathlib, re, sys

ROOT = pathlib.Path(__file__).resolve().parents[2]
ENGINE = ROOT / "FutureVoice/Services/TopicEngine.swift"
COMPOSER = ROOT / "FutureVoice/Views/ScenarioComposerSheet.swift"
OUT = ROOT / "android/app/src/main/java/com/roro/futurevoice/talk/PathIdeasContent.kt"

src = ENGINE.read_text()


def dedent(block: str) -> str:
    lines = block.split("\n")
    indent = min((len(l) - len(l.lstrip()) for l in lines if l.strip()), default=0)
    return "\n".join(l[indent:] if l.strip() else "" for l in lines)


MAP = {
    r'\(c.name)': "$personName",
    r'\(c.relationship.isEmpty ? "" : " (\(c.relationship))")': "$relationshipSuffix",
    r"\(count)": "$count",
    r"\(LanguageCatalog.englishName(targetLanguage))": "$languageName",
    r"\(withPerson)": "$withPerson",
    r"\(levelGuidance)": "$levelGuidance",
}


def kotlinize(text: str) -> str:
    for swift, kotlin in MAP.items():
        text = text.replace(swift, kotlin)
    if r"\(" in text:
        sys.exit("unmapped interpolation: " + re.search(r"\\\([^)]*\)", text).group(0))
    stray = re.sub(r"\$(personName|relationshipSuffix|count|languageName|withPerson|levelGuidance)\b", "", text)
    if "$" in stray:
        sys.exit("literal '$' in prompt — escape it before generating")
    return text


fn = re.search(r"private static func pathSystemPrompt\(.*?\n    \}", src, re.S)
if not fn:
    sys.exit("could not find pathSystemPrompt")
body = fn.group(0)
literals = re.findall(r'"""\n(.*?)\n\s*"""', body, re.S)
if len(literals) != 4:
    sys.exit(f"expected 4 literals in pathSystemPrompt, found {len(literals)}")
with_person, shallow, deep, shell = (kotlinize(dedent(l)) for l in literals)

# The shipped sub-areas: level 1 of a preset category is the same for
# everyone, so waiting on the model for it buys nothing.
seeds_block = re.search(r"private static let seeds: \[String: \[SuggestedTopic\]\] = \[(.*?)\n    \]", src, re.S)
if not seeds_block:
    sys.exit("could not find the seeds table")
seeds = []
for key, items in re.findall(r'"([a-z ]+)": \[(.*?)\n        \]', seeds_block.group(1), re.S):
    rows = re.findall(r'\.init\(title: "((?:[^"\\]|\\.)*)", blurb: "((?:[^"\\]|\\.)*)"\)', items)
    if not rows:
        sys.exit(f"no seeds parsed for {key}")
    seeds.append((key, rows))
if not seeds:
    sys.exit("no seed categories parsed")

presets = re.search(r"static let presets: \[Category\] = \[(.*?)\n    \]", COMPOSER.read_text(), re.S)
if not presets:
    sys.exit("could not find the preset categories")
cats = re.findall(r'\.init\(title:\s*"([^"]+)",\s*icon:\s*"([^"]+)"\)', presets.group(1))
if not cats:
    sys.exit("no preset categories parsed")


def q(s: str) -> str:
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"').replace("$", "\\$") + '"'


seed_kt = ",\n".join(
    "        " + q(key) + " to listOf(\n"
    + ",\n".join(f"            Seed({q(t)}, {q(b)})" for t, b in rows)
    + ",\n        )"
    for key, rows in seeds)
cats_kt = ",\n".join(f"        Category({q(t)}, {q(i)})" for t, i in cats)

OUT.write_text(f'''package com.roro.futurevoice.talk

// GENERATED by scripts/android/gen-path-ideas.py — do not edit.
// Source: FutureVoice/Services/TopicEngine.swift (pathSystemPrompt, seeds),
//         FutureVoice/Views/ScenarioComposerSheet.swift (presets).

object PathIdeasContent {{
    class Seed(val title: String, val blurb: String)
    class Category(val title: String, val icon: String)

    /** The composer's preset categories, in the shipped order. */
    val categories: List<Category> = listOf(
{cats_kt},
    )

    /** Level 1 of a preset category: shipped, zero round-trip. The sub-areas
     *  of "Cafe" are the same for everyone, and waiting on the model for them
     *  cost the learner the whole pause right after their first tap. */
    val seeds: Map<String, List<Seed>> = mapOf(
{seed_kt},
    )

    fun seedSubAreas(category: String): List<Seed>? = seeds[category.lowercase()]

    fun systemPrompt(languageName: String, count: Int, depth: Int,
                     personName: String?, relationship: String): String {{
        val relationshipSuffix = if (relationship.isBlank()) "" else " ($relationship)"
        val withPerson = if (personName == null) "" else """{with_person}""".trimIndent()
        val levelGuidance = if (depth <= 1) """{shallow}""".trimIndent() else """{deep}""".trimIndent()
        return """{shell}""".trimIndent()
    }}
}}
''')
print(f"wrote {OUT.relative_to(ROOT)} ({len(cats)} categories, {len(seeds)} seeded, "
      f"{sum(len(r) for _, r in seeds)} seed chips)")
