#!/usr/bin/env python3
"""Lift ConversationEngine.correctionOnlyPrompt out of the Swift source.

On the realtime call path the reply is prose and the correction is a
SEPARATE, later request — this is the prompt for that request. It is
content: retyped, the two platforms would judge the same spoken line by
different rules, and the ASR guards (drop / digit / contraction) are exactly
the lines a retype loses. So it is extracted, never copied by hand.

    python3 scripts/android/gen-correction-prompt.py

Fails loudly on any interpolation it does not know how to map.
"""
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parents[2]
SWIFT = ROOT / "FutureVoice/Services/ConversationEngine.swift"
OUT = ROOT / "android/app/src/main/java/com/roro/futurevoice/talk/CorrectionOnlyPrompt.kt"

src = SWIFT.read_text()
m = re.search(
    r'static func correctionOnlyPrompt\(.*?\{\s*'
    r'let targetName = .*?\n\s*let nativeName = .*?\n\s*return """\n(.*?)\n\s*"""',
    src, re.S)
if not m:
    sys.exit("could not find correctionOnlyPrompt's literal")

body = m.group(1)
lines = body.split("\n")
indent = min((len(l) - len(l.lstrip()) for l in lines if l.strip()), default=0)
text = "\n".join(l[indent:] if l.strip() else "" for l in lines)

# The interpolations the Swift literal uses, mapped to Kotlin template
# names. Anything else is an unmapped interpolation → fail. The guards are
# appended at LINE ENDS and are empty for every other target, so each
# language's prompt stays byte-identical to what iOS sends.
mapping = {
    r"\(targetName)": "$targetName",
    r"\(nativeName)": "$nativeName",
    r"\(level.rawValue)": "$levelCode",
    r"\(scriptGuard(targetLanguage))": "$scriptGuard",
    r"\(spacingGuard(targetLanguage))": "$spacingGuard",
    r"\(registerGuard(targetLanguage))": "$registerGuard",
}


def func_body(name: str) -> str:
    """The body of `static func <name>(...)` — braces balanced."""
    i = src.index(f"static func {name}(")
    j = src.index("{", i)
    depth, k = 0, j
    while True:
        c = src[k]
        depth += c == "{"
        depth -= c == "}"
        k += 1
        if depth == 0:
            return src[j + 1:k - 1]


def literals(chunk: str) -> str:
    """Concatenated Swift string literals in `chunk`, as one Kotlin literal body."""
    parts = re.findall(r'"((?:[^"\\]|\\.)*)"', chunk)
    joined = "".join(parts)
    return joined.replace("$", "\\$")


def guard_chunks(name: str):
    """(common, {lang: extra}) for a guard: the text every gated language gets,
    and the per-language additions under `if base == "xx" {`."""
    body = func_body(name)
    body = re.sub(r"guard .*?else \{ return \"\" \}", "", body, count=1)
    extras = {}
    for lang, block in re.findall(r'if base == "(\w+)" \{(.*?)\n        \}', body, re.S):
        extras[lang] = literals(block)
    common = literals(re.sub(r'if base == "\w+" \{.*?\n        \}', "", body, flags=re.S))
    return common, extras


spacing, _ = guard_chunks("spacingGuard")
script, _ = guard_chunks("scriptGuard")
register, register_extra = guard_chunks("registerGuard")
if not spacing or not script or not register or set(register_extra) != {"ko", "ja"}:
    sys.exit("a guard's shape changed — spacing/script/register(ko, ja) expected")
for k, v in mapping.items():
    text = text.replace(k, v)
if r"\(" in text:
    sys.exit("prompt carries an interpolation this script doesn't map: "
             + re.search(r"\\\([^)]*\)", text).group(0))

# Kotlin raw strings can't escape `$`; only our own placeholders may remain.
stray = re.sub(r"\$(targetName|nativeName|levelCode|scriptGuard|spacingGuard|registerGuard)\b", "", text)
if "$" in stray:
    sys.exit("prompt carries a literal '$' — escape it before generating")

register_ko = register_extra['ko']
register_ja = register_extra['ja']
OUT.write_text(f'''package com.roro.futurevoice.talk

// GENERATED by scripts/android/gen-correction-prompt.py — do not edit.
// Source: FutureVoice/Services/ConversationEngine.swift (correctionOnlyPrompt).

import com.roro.futurevoice.data.CefrLevel
import com.roro.futurevoice.data.LanguageCatalog

/**
 * The correction request on the realtime path. The reply is prose and the
 * voice is already playing by the time this fires — nothing the learner hears
 * ever waits on coaching. Extracted from the Swift source so both platforms
 * judge a spoken line by the same rules, ASR guards included.
 */
object CorrectionOnlyPrompt {{

    /** Japanese only: the recognizer, not the learner, decides kanji or kana. */
    private fun scriptGuard(targetLanguage: String): String =
        if (targetLanguage.substringBefore('-') != "ja") "" else "{script}"

    /** Korean only: word spacing is the recognizer's (띄어쓰기). */
    private fun spacingGuard(targetLanguage: String): String =
        if (targetLanguage.substringBefore('-') != "ko") "" else "{spacing}"

    /** Korean and Japanese: the speech level is the learner's, never a slip. */
    private fun registerGuard(targetLanguage: String): String =
        when (targetLanguage.substringBefore('-')) {{
            "ko" -> "{register}" + "{register_ko}"
            "ja" -> "{register}" + "{register_ja}"
            else -> ""
        }}

    fun build(targetLanguage: String, nativeLanguage: String, level: CefrLevel): String {{
        val targetName = LanguageCatalog.englishName(targetLanguage)
        val nativeName = LanguageCatalog.englishName(nativeLanguage)
        val levelCode = level.code.uppercase()
        val scriptGuard = scriptGuard(targetLanguage)
        val spacingGuard = spacingGuard(targetLanguage)
        val registerGuard = registerGuard(targetLanguage)
        return """{text}""".trimIndent()
    }}
}}
''')
print(f"wrote {OUT.relative_to(ROOT)} ({len(text)} chars)")
