#!/usr/bin/env python3
"""Lift ConversationEngine.contractionExpansions out of the Swift source.

The table is CONTENT: it decides which corrections are dropped as "the same
words" (dictation expands contractions, so a learner who said "I'm" is
transcribed "I am" and gets told they made a mistake they didn't make) and
which words light up as changed. Retyped, the two platforms would judge the
same spoken line differently.

    python3 scripts/android/gen-contractions.py
"""
import pathlib, re, sys

ROOT = pathlib.Path(__file__).resolve().parents[2]
SWIFT = ROOT / "FutureVoice/Services/ConversationEngine.swift"
OUT = ROOT / "android/app/src/main/java/com/roro/futurevoice/talk/SpokenWordsContent.kt"

block = re.search(r"private static let contractionExpansions: \[\(String, String\)\] = \[(.*?)\n    \]",
                  SWIFT.read_text(), re.S)
if not block:
    sys.exit("could not find contractionExpansions")
pairs = re.findall(r'\("([^"]+)",\s*"([^"]+)"\)', block.group(1))
if len(pairs) < 20:
    sys.exit(f"only {len(pairs)} pairs parsed — the literal's shape changed")

rows = ",\n".join(f'        "{a}" to "{b}"' for a, b in pairs)
OUT.write_text(f'''package com.roro.futurevoice.talk

// GENERATED by scripts/android/gen-contractions.py — do not edit.
// Source: FutureVoice/Services/ConversationEngine.swift (contractionExpansions).

/**
 * Contracted → expanded, applied to BOTH sides so either direction of the
 * rewrite collapses. Word-boundary-free on purpose: these strings can't occur
 * inside a longer word once the apostrophe is required.
 */
object SpokenWordsContent {{
    val contractions: List<Pair<String, String>> = listOf(
{rows},
    )
}}
''')
print(f"wrote {OUT.relative_to(ROOT)} ({len(pairs)} pairs)")
