#!/usr/bin/env python3
"""Lift ConversationEngine's FIRST CALL block out of the Swift source.

The block is how the fluent self meets the learner on the very first free
talk — it introduces itself first, asks one thing at a time, and refuses to
run an intake form. It is prompt content; retyped, iOS and Android would meet
the same learner differently.

    python3 scripts/android/gen-first-call-block.py
"""
import pathlib, re, sys
ROOT = pathlib.Path(__file__).resolve().parents[2]
SRC = ROOT / "FutureVoice/Services/ConversationEngine.swift"
OUT = ROOT / "android/app/src/main/java/com/roro/futurevoice/talk/FirstCallBlock.kt"
src = SRC.read_text()
m = re.search(r'let firstMeetingBlock = \(firstMeeting && counterpart == nil\) \? """\n(.*?)\n\s*""" : ""', src, re.S)
if not m: sys.exit("no FIRST CALL literal")
# Swift's trailing `\` joins lines; honour it, then strip the closing indent.
body = re.sub(r"\\\n\s*", " ", m.group(1))
lines = body.split("\n")
indent = min((len(l) - len(l.lstrip()) for l in lines if l.strip()), default=0)
text = "\n".join(l[indent:] if l.strip() else "" for l in lines)
text = text.replace(r"\(languageName)", "$languageName")
if r"\(" in text: sys.exit("unmapped interpolation")
if "$" in re.sub(r"\$languageName\b", "", text): sys.exit("literal $")
OUT.write_text(f'''package com.roro.futurevoice.talk

// GENERATED by scripts/android/gen-first-call-block.py — do not edit.
// Source: FutureVoice/Services/ConversationEngine.swift (firstMeetingBlock).

/** Spliced into the system prompt on the first free talk (`metAt == null`). */
object FirstCallBlock {{
    fun build(languageName: String): String = """{text}"""
}}
''')
print(f"wrote {OUT.relative_to(ROOT)} ({len(text)} chars)")
