#!/usr/bin/env python3
"""Lift ShadowTranscriber's transcribe prompt out of the Swift source.

A shadow transcript is not context for a model — it IS the grade: the diff,
the score and the coach bullets are all computed from it. Retyped, the two
platforms would grade the same take by different instructions, and the lines
a retype loses are exactly the load-bearing ones ("you are NOT told which
sentence they were copying", "never complete a sentence", "a word you supply
that was never spoken is a mark the learner did not earn"). So it is
extracted, never copied by hand.

    python3 scripts/android/gen-shadow-transcribe-prompt.py

Fails loudly on any interpolation it does not know how to map.
"""
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parents[2]
SWIFT = ROOT / "FutureVoice/Services/ShadowTranscriber.swift"
OUT = ROOT / "android/app/src/main/java/com/roro/futurevoice/talk/ShadowTranscribePrompt.kt"

src = SWIFT.read_text()
m = re.search(
    r'private static func prompt\(targetLanguage: String\) -> String \{\s*'
    r'let target = .*?\n\s*return """\n(.*?)\n\s*"""',
    src, re.S)
if not m:
    sys.exit("could not find ShadowTranscriber.prompt's literal")

body = m.group(1)
lines = body.split("\n")
indent = min((len(l) - len(l.lstrip()) for l in lines if l.strip()), default=0)
text = "\n".join(l[indent:] if l.strip() else "" for l in lines)

mapping = {r"\(target)": "$target"}
for k, v in mapping.items():
    text = text.replace(k, v)
if r"\(" in text:
    sys.exit("prompt carries an interpolation this script doesn't map: "
             + re.search(r"\\\([^)]*\)", text).group(0))

# Kotlin raw strings can't escape `$`; only our own placeholder may remain.
if "$" in re.sub(r"\$target\b", "", text):
    sys.exit("prompt carries a literal '$' — escape it before generating")

OUT.write_text(f'''package com.roro.futurevoice.talk

// GENERATED by scripts/android/gen-shadow-transcribe-prompt.py — do not edit.
// Source: FutureVoice/Services/ShadowTranscriber.swift (prompt).

import com.roro.futurevoice.data.LanguageCatalog

/**
 * What the model is told when it reads a shadowing take.
 *
 * It is never shown the target sentence: it could only copy it, and a word
 * the model supplies is a mark the learner did not earn. Extracted from the
 * Swift source so a take is graded by the same instructions on both
 * platforms.
 */
object ShadowTranscribePrompt {{
    fun build(targetLanguage: String): String {{
        val target = LanguageCatalog.englishName(targetLanguage)
        return """{text}""".trimIndent()
    }}
}}
''')
print(f"wrote {OUT.relative_to(ROOT)} ({len(text)} chars)")
