#!/usr/bin/env python3
"""Lift ShadowEngine's coach prompt (system + user message) out of the Swift source.

The three bullets a learner reads between shadow attempts are written from
these instructions, and the user message is the EVIDENCE they are anchored
to (the diff, the duration ratio, the off-beat words). Retyped, the two
platforms would coach the same take differently — and the lines a retype
drops are the load-bearing ones ("treat the diff as ground truth", "you have
no pitch data, so never claim to hear intonation", the field-by-field
language rule). So it is extracted, never copied by hand.

    python3 scripts/android/gen-shadow-coach-prompt.py

Fails loudly on any interpolation it does not know how to map.
"""
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parents[2]
SWIFT = ROOT / "FutureVoice/Services/ShadowEngine.swift"
OUT = ROOT / "android/app/src/main/java/com/roro/futurevoice/talk/ShadowCoachPrompt.kt"

src = SWIFT.read_text()


def literal(func_pattern: str, what: str) -> str:
    m = re.search(func_pattern + r'.*?return """\n(.*?)\n\s*"""', src, re.S)
    if not m:
        sys.exit(f"could not find ShadowEngine.{what}'s literal")
    lines = m.group(1).split("\n")
    indent = min((len(l) - len(l.lstrip()) for l in lines if l.strip()), default=0)
    text = "\n".join(l[indent:] if l.strip() else "" for l in lines)
    # Swift: a backslash at the end of a line inside a multi-line literal
    # joins it to the next line (no newline). Kotlin has no such thing.
    text = re.sub(r"\\\n", "", text)
    return text


def kotlinize(text: str, mapping: dict, what: str) -> str:
    for k, v in mapping.items():
        text = text.replace(k, v)
    if r"\(" in text:
        sys.exit(f"{what} carries an interpolation this script doesn't map: "
                 + re.search(r"\\\([^)]*\)", text).group(0))
    allowed = {v for v in mapping.values()}
    stripped = text
    for v in allowed:
        stripped = stripped.replace(v, "")
    if "$" in stripped:
        sys.exit(f"{what} carries a literal '$' — escape it before generating")
    if '"""' in text:
        sys.exit(f"{what} carries a triple quote")
    return text


system = kotlinize(
    literal(r"static func systemPrompt\(targetLanguage: String,", "systemPrompt"),
    {r"\(LanguageCatalog.englishName(targetLanguage))": "${targetName}",
     r"\(nativeName)": "${nativeName}"},
    "systemPrompt")
user = kotlinize(
    literal(r"static func userMessage\(", "userMessage"),
    {r"\(targetText)": "${targetText}",
     r'\(learnerText.isEmpty ? "(empty)" : learnerText)': "${learnerShown}",
     r"\(targetDurationMs)": "${targetDurationMs}",
     r"\(learnerDurationMs)": "${learnerDurationMs}",
     r"\(ratio)": "${ratio}",
     r"\(renderDiffForPrompt(diffSteps))": "${diff}",
     r"\(renderRhythmForPrompt(rhythm))": "${rhythmText}"},
    "userMessage")

OUT.write_text(f'''package com.roro.futurevoice.talk

// GENERATED by scripts/android/gen-shadow-coach-prompt.py — do not edit.
// Source: FutureVoice/Services/ShadowEngine.swift (systemPrompt, userMessage).

import com.roro.futurevoice.data.LanguageCatalog

/**
 * The shadow coach: three native-language bullets (pronunciation · pacing ·
 * try this) anchored to the deterministic diff and the measured beat. The
 * numeric score is computed in code and never asked of the model.
 */
object ShadowCoachPrompt {{
    fun system(targetLanguage: String, nativeLanguage: String): String {{
        val targetName = LanguageCatalog.englishName(targetLanguage)
        val nativeName = LanguageCatalog.englishName(nativeLanguage)
        return """{system}"""
    }}

    fun userMessage(
        targetText: String,
        learnerText: String,
        targetDurationMs: Int,
        learnerDurationMs: Int,
        diffSteps: List<ShadowScore.DiffStep>,
        rhythm: ShadowScore.RhythmAnalysis?,
    ): String {{
        val ratio = if (targetDurationMs > 0)
            String.format(java.util.Locale.US, "%.2f", learnerDurationMs.toDouble() / targetDurationMs)
        else "n/a"
        val learnerShown = if (learnerText.isEmpty()) "(empty)" else learnerText
        val diff = ShadowScore.renderDiffForPrompt(diffSteps)
        val rhythmText = ShadowScore.renderRhythmForPrompt(rhythm)
        return """{user}"""
    }}
}}
''')
print(f"wrote {OUT.relative_to(ROOT)} (system {len(system)} chars, user {len(user)} chars)")
