#!/usr/bin/env python3
"""Lift PersonaParser's polish prompt out of the Swift source into Kotlin.

The prompt is CONTENT, and content that is retyped drifts: two platforms end
up polishing the same spoken answer into two different profiles, and the
difference only shows up months later in how the fluent self talks about the
learner's life. So it is extracted, never copied by hand.

Run after touching PersonaParser.systemPrompt():

    python3 scripts/android/gen-persona-polish.py

Fails loudly rather than emitting a half-prompt — an interpolation in the
Swift literal has no Kotlin equivalent here, and silently dropping it would
ship a prompt missing a rule.
"""
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parents[2]
SWIFT = ROOT / "FutureVoice/Services/PersonaParser.swift"
OUT = ROOT / "android/app/src/main/java/com/roro/futurevoice/net/PersonaPolishPrompt.kt"

src = SWIFT.read_text()
m = re.search(r'private static func systemPrompt\(\) -> String \{\s*"""\n(.*?)\n\s*"""', src, re.S)
if not m:
    sys.exit("could not find systemPrompt()'s literal in PersonaParser.swift")

body = m.group(1)

# Swift strips the closing delimiter's indentation from every line.
lines = body.split("\n")
indent = min((len(l) - len(l.lstrip()) for l in lines if l.strip()), default=0)
text = "\n".join(l[indent:] if l.strip() else "" for l in lines)

if "\\(" in text:
    sys.exit("prompt carries a Swift interpolation; port it by hand and update this script")

# A Kotlin raw string cannot contain a raw `$`, and the prompt has none today.
if "$" in text:
    sys.exit("prompt carries a '$'; escape it for Kotlin's raw string first")

OUT.write_text(f'''package com.roro.futurevoice.net

// GENERATED by scripts/android/gen-persona-polish.py — do not edit.
// Source: FutureVoice/Services/PersonaParser.swift (systemPrompt()).

/**
 * The polish pass that turns a rambling spoken answer into compact profile
 * text. Same field in, same field out — it drops restarts and filler and
 * keeps every concrete detail.
 *
 * Extracted from the Swift source so the two platforms cannot drift: a
 * retyped prompt polishes the same answer into two different profiles, and
 * the difference only surfaces months later in how the fluent self talks
 * about the learner's life.
 */
object PersonaPolishPrompt {{
    const val SYSTEM: String = """{text}"""
}}
''')
print(f"wrote {OUT.relative_to(ROOT)} ({len(text)} chars)")
