#!/usr/bin/env python3
"""Lift `CoachingLanguage.breathPunctuation` out of the Swift source.

It is the rule that keeps a synthesized line from being read without
breathing, and it is spliced into every prompt whose text is SPOKEN — the
call, the scene, the openers, the voicemail. Retyped, the two platforms would
punctuate their speech differently, so it is extracted.

    python3 scripts/android/gen-breath-punctuation.py
"""
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parents[2]
SWIFT = ROOT / "FutureVoice/Services/CoachingLanguage.swift"
OUT = ROOT / "android/app/src/main/java/com/roro/futurevoice/talk/CoachingLanguage.kt"

m = re.search(r'static let breathPunctuation = """\n(.*?)\n\s*"""', SWIFT.read_text(), re.S)
if not m:
    sys.exit("no breathPunctuation literal")

# The Swift literal uses `\` line continuations: those lines join with a
# single space, the rest keep their newline.
text = ""
for line in (l.strip() for l in m.group(1).split("\n")):
    text += (line[:-1].rstrip() + " ") if line.endswith("\\") else (line + "\n")
text = text.strip()
if '"""' in text or "$" in text:
    sys.exit("prompt carries a sequence a Kotlin raw string can't hold")

OUT.write_text(f'''package com.roro.futurevoice.talk

// GENERATED by scripts/android/gen-breath-punctuation.py — do not edit.
// Source: FutureVoice/Services/CoachingLanguage.swift (breathPunctuation).

/**
 * The shared rule for text that will be SPOKEN. The synthesizer pauses at
 * punctuation and nowhere else, so a line with none is read without
 * breathing — measured on both TTS models and on the gateway's per-sentence
 * path. Spliced into every prompt whose output is read aloud.
 */
object CoachingLanguage {{
    const val breathPunctuation = """{text}"""
}}
''')
print(f"wrote {OUT.relative_to(ROOT)} ({len(text)} chars)")
