#!/usr/bin/env python3
"""Lift CounterpartParser's plain parse prompt out of the Swift source into Kotlin.

The prompt is CONTENT, and retyped content drifts: the two platforms would file
the same spoken description of a friend into two different profiles. So it is
extracted, never copied by hand. The public-figure variant lives in
`PublicFigureLookup.kt`.

    python3 scripts/android/gen-counterpart-parser.py

Fails loudly on any interpolation other than `\\(nativeName)`.
"""
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parents[2]
SWIFT = ROOT / "FutureVoice/Services/CounterpartParser.swift"
OUT = ROOT / "android/app/src/main/java/com/roro/futurevoice/talk/CounterpartParsePrompt.kt"

src = SWIFT.read_text()
m = re.search(r'private static func systemPrompt\(nativeLanguage: String, publicFigure: Bool\) -> String \{.*?return """\n(.*?)\n\s*"""', src, re.S)
if not m:
    sys.exit("could not find systemPrompt()'s literal in CounterpartParser.swift")

lines = m.group(1).split("\n")
indent = min((len(l) - len(l.lstrip()) for l in lines if l.strip()), default=0)
text = "\n".join(l[indent:] if l.strip() else "" for l in lines)

if "$" in text:
    sys.exit("prompt carries a '$'; escape it for Kotlin's raw string first")
text = text.replace("\\(nativeName)", "${nativeName}")
if "\\(" in text:
    sys.exit("prompt carries an unknown Swift interpolation; port it by hand and update this script")
if '"""' in text:
    sys.exit("prompt carries a triple quote")

OUT.write_text(f'''package com.roro.futurevoice.talk

// GENERATED by scripts/android/gen-counterpart-parser.py — do not edit.
// Source: FutureVoice/Services/CounterpartParser.swift (systemPrompt, plain parse).

/**
 * Turns the learner's spoken description of someone they know into profile
 * fields, every one in the learner's NATIVE language — it is their own note
 * about their own friend.
 */
object CounterpartParsePrompt {{
    fun system(nativeName: String): String = """{text}"""
}}
''')
print(f"wrote {OUT.relative_to(ROOT)} ({len(text)} chars)")
