package com.roro.futurevoice.talk

import com.roro.futurevoice.data.CefrLevel

// GENERATED by scripts/android/gen-coach-prompts.py --ref ebf848e — do not edit.
// Source: FutureVoice/Services/ConversationEngine.swift (speechScale vocabulary,
// beginnerQuestions) and FutureVoice/Services/CoachMode.swift (CoachSuggester.system).

object CoachPrompts {
    /** iOS `ConversationEngine.speechScale(for:).vocabulary`. */
    fun speechVocabulary(level: CefrLevel): String = when (level) {
        CefrLevel.A1, CefrLevel.A2 ->
        "Use the most ORDINARY everyday words — the ones this learner\n  already hears every day. No academic, technical, literary or\n  business register. At most ONE idiom or phrasal verb per turn,\n  and only when the situation makes its meaning obvious. When a\n  precise word would be hard, say the easy thing instead of the\n  clever thing (\"it got worse\", not \"it deteriorated\")."
        CefrLevel.B1, CefrLevel.B2 ->
        "Everyday vocabulary plus the common idioms and phrasal verbs a\n  fluent speaker actually reaches for. Specialist or abstract\n  words are fine when the sentence around them makes the meaning\n  clear; drop one genuinely new word in now and then, not every\n  turn."
        CefrLevel.C1, CefrLevel.C2 ->
        "Speak with your full natural range — idiom, precise nuance\n  words, register shifts, the odd bit of wordplay. Don't\n  simplify; this learner is here for the parts they can't\n  produce yet."
    }

    /**
     * iOS `ConversationEngine.beginnerQuestions`: how the fluent self ASKS an
     * A1/A2 learner. Empty at B1 and above, so those prompts stay byte for
     * byte what they were.
     */
    fun beginnerQuestions(level: CefrLevel): String {
        if (level != CefrLevel.A1 && level != CefrLevel.A2) return ""
        return "\n\nHOW TO ASK — THIS LEARNER IS A BEGINNER (" +
        level.code.uppercase() +
        "). Answering is the hard part for them, so every question you ask has to be one they can answer. These rules OUTRANK everything above about questions, following threads, and not ending on a question:\n- End EVERY turn with exactly ONE question, as the last thing you say.   Never two questions in a turn. Two choices inside one question are   fine (\"Coffee or tea?\").\n- Make it CONCRETE: answerable in a few words with a plain fact from   their life — a name, a place, a time, a thing, yes or no, or one of   two choices. \"Where do you live?\" \"Do you work or study?\" \"What time   do you get up?\"\n- NEVER an open question that makes them build the answer: no \"tell   me about…\", \"how was…\", \"how is your day going\", \"what do you   think about…\", \"what's it like…\", \"what kind of…\", \"why…\". After   several concrete answers about the same thing, one simple \"Do you   like it?\" is the most open it gets.\n- Walk ONE subject in small steps: a small question, their answer,   the next small question about the same thing. Getting to know   them is \"What's your name?\" → \"Where do you live?\" → \"What do you   do?\" — one per turn — never \"Tell me about yourself.\"\n- Keep the question SHORT (about 3–7 words) and keep what comes   before it short too: one short reaction, then the question. They   need the question, not a speech.\n- React to every answer, however small, in a few warm words   (\"Busan! Nice.\"). If their answer had a mistake, say it back the   right way inside that reaction, without pointing at it (\"Ah, you   went to work, then home.\").\n- If they get stuck, go quiet, or answer in another language: don't   press and don't change the subject — ask the same thing more   easily, as two choices (\"Do you live in a city, or a small town?\")."
    }

    /** iOS `CoachSuggester.system(target:native:level:)`. */
    fun suggesterSystem(targetName: String, nativeName: String, level: CefrLevel): String =
        "A " +
        level.code.uppercase() +
        " learner of " +
        targetName +
        " is on a spoken call. The other speaker has just said the line below. Write ONE short thing the learner could say back next — exactly what a native speaker would actually say out loud in that moment, kept easy. Never a textbook sentence: if a native would not say it that way, it is wrong however simple it is.\n\n- SPOKEN, not written: contractions where speech has them (\"I'll\",   \"I'm\", \"don't\"), the everyday phrasing people really use in that   place (\"Can I get a latte?\", \"I'll have the pasta\", \"Just looking,   thanks\"), never a stiff full form (\"I will have a coffee please\").\n  When a situation is given, answer as a real customer, guest or   caller there would. One answer, one idea — not \"just looking\" AND   a request — and \"please\" only on a request, never on a statement   (\"I'm going to London, please\").\n\n- \"say\": in " +
        targetName +
        " ONLY — always, even when the line contains   names or words in another language. 3–10 words, one sentence (two   very short ones at most). " +
        speechVocabulary(level) +
        "\n- Where the answer depends on something only the learner knows (their   name, a time, a place, what they did, what they like, which drink   or dish or item they want), put a   plausible EXAMPLE in square brackets — \"I usually get up at [7].\" —   which the learner swaps for their own. It is shown faded as a   placeholder, so it is never a claim about them. One or two   brackets, a word or two inside each, nothing else in brackets.\n- If the line asks nothing, \"say\" is a natural reaction or a short   follow-up question back.\n- Use the same form of address the other speaker uses with them   (Korean 반말 or 존댓말, Japanese plain or polite, du or Sie, tu or   vous…).\n- \"meaning\": the " +
        nativeName +
        " translation, natural, with the   bracketed example translated inside brackets in the matching place.\n- \"word\": if studied items are listed and one fits this answer   naturally — in its usual sense, carrying what the answer means —   use it in \"say\" and return it exactly as listed. Otherwise null,   which is the usual case. Never force one in.\n\nReturn STRICT JSON only: {\"say\": \"...\", \"meaning\": \"...\", \"word\": null}"
}
