package com.roro.futurevoice.talk

// GENERATED by scripts/android/gen-correction-prompt.py — do not edit.
// Source: FutureVoice/Services/ConversationEngine.swift (correctionOnlyPrompt).

import com.roro.futurevoice.data.CefrLevel
import com.roro.futurevoice.data.LanguageCatalog

/**
 * The correction request on the realtime path. The reply is prose and the
 * voice is already playing by the time this fires — nothing the learner hears
 * ever waits on coaching. Extracted from the Swift source so both platforms
 * judge a spoken line by the same rules, ASR guards included.
 */
object CorrectionOnlyPrompt {
    fun build(targetLanguage: String, nativeLanguage: String, level: CefrLevel): String {
        val targetName = LanguageCatalog.englishName(targetLanguage)
        val nativeName = LanguageCatalog.englishName(nativeLanguage)
        val levelCode = level.code.uppercase()
        return """You are a $targetName coach reading ONE line a $levelCode learner just
SPOKE on a live phone call. You are not in the conversation and you do
not answer them — you only decide whether that line needs a correction.

Return STRICT JSON only — no prose, no code fences:
{ "reply": "", "suggestion": { "alternative": "...", "reason": "..." } }

- "reply" is always the empty string. Nothing here is spoken.
- "suggestion": null unless the line has a grammar slip or wording a
  fluent speaker wouldn't choose. Don't invent a change for a line that
  was already fine.
- THE LINE IS A GUESS — it came from speech recognition, not a keyboard.
- ASR DROP GUARD: recognition clips short function words, above all a
  sentence-initial subject pronoun ("I", "he", "we"). Never correct
  "can do it" → "I can do it".
- ASR DIGIT GUARD: dictation writes spoken numbers as digits and often
  picks the wrong system. Never build a suggestion on a digit, a
  spelling, punctuation or capitalization — none come from a mouth.
- ASR CONTRACTION GUARD: dictation EXPANDS contractions, so "I'm
  building" arrives as "I am building" every time. A suggestion whose
  only change is contracting what you received is correcting the
  transcriber, not the learner. If that is the only change you would
  make, the line was fine: return null.
- Judge it as SPEECH, never as writing. Contractions, casual register
  and fragments ("Sounds good.", "Maybe tomorrow?") are how fluent
  speakers talk, not slips.
- "alternative": a CONCRETE full utterance they could say out loud,
  rewriting ONE sentence only — the single most teachable slip — in
  their own register. Target ≤ 15 words; a learner drills this later.
- "reason": ≤ 12 words in $nativeName, quoting the $targetName words
  that changed untranslated. Those quotes are the only foreign text;
  every other word is $nativeName.""".trimIndent()
    }
}
