package com.roro.futurevoice.talk

// GENERATED by scripts/android/gen-counterpart-ideas.py — do not edit.
// Source: FutureVoice/Services/TopicEngine.swift (counterpartSystemPrompt, FallbackText).

object CounterpartIdeasContent {
    fun systemPrompt(languageName: String, count: Int): String = """You generate $count realistic $languageName-language scenarios where
the USER and a specific COUNTERPART would meet, interact, or talk —
anchored on their actual relationship and shared life context.

Think situations like:
  - "Bumping into them at Kita pickup, talking about the new teacher"
  - "At a kid's birthday party, killing time at the snack table"
  - "Sunday morning football, recovering between matches"
  - "Playdate at the playground while the kids run wild"
  - "1-on-1 with your manager about next quarter's priorities"
  - "Catching up over coffee after they got back from a trip"

Match the COUNTERPART's role and how they know the user. Avoid
textbook clichés ("ordering coffee") unless that fits this specific
pair's actual life. Use shared context (background, common topics) so
each scenario feels like THIS pair, not interchangeable.

Return STRICT JSON only — no prose, no code fences:
{ "topics": [ { "title": "...", "blurb": "..." } ] }

Rules:
- title: ≤ 60 chars in $languageName. Concrete moment with a hook.
- blurb: ≤ 140 chars in $languageName. One line of context that the avatar
  can use as a seed for the opening of the dialogue.
- Vary scenarios across the relationship's natural surfaces — don't
  have three about the same setting.""".trimIndent()

    class Fallback(val catchUpWithFormat: String, val catchUpBlurb: String, val onYourMind: String, val onYourMindBlurb: String)

    private val fallbacks = mapOf(
        "en" to Fallback("A quick catch-up with %s", "Open with what's been on your mind lately.", "Something on your mind you've been meaning to bring up", "Pick a real-life thing you'd actually want their take on."),
        "de" to Fallback("Kurz mit %s auf den neuesten Stand kommen", "Fang damit an, was dir in letzter Zeit im Kopf herumgeht.", "Etwas, das dir auf der Seele liegt und das du ansprechen wolltest", "Nimm etwas Echtes, wozu du wirklich ihre Meinung hören willst."),
        "ko" to Fallback("%s와 짧게 근황 나누기", "요즘 마음에 걸리던 것부터 꺼내보세요.", "말하려고 벼르던, 마음에 걸리는 이야기", "상대의 의견이 진짜 궁금한 실제 일을 골라보세요."),
    )

    fun fallback(languageCode: String): Fallback = fallbacks[languageCode] ?: fallbacks.getValue("en")
}
