package com.roro.futurevoice.talk

// GENERATED by scripts/android/gen-counterpart-parser.py — do not edit.
// Source: FutureVoice/Services/CounterpartParser.swift (systemPrompt, plain parse).

/**
 * Turns the learner's spoken description of someone they know into profile
 * fields, every one in the learner's NATIVE language — it is their own note
 * about their own friend.
 */
object CounterpartParsePrompt {
    fun system(nativeName: String): String = """The user just described a person they know — someone they'd practice
speaking their target language with in a simulated dialogue. The description was
spoken, so it may be casual, contain restarts, or trail off. Extract
a structured profile.

Write EVERY field in ${nativeName}, the language the user spoke in.
This profile is the user's own note about their own friend: they read
it on the person's card and edit it by hand. Handing back an English
translation of what they just said in ${nativeName} means they have to
re-read and re-edit their own words in a foreign language. The name
stays in the original script the user used.

Return STRICT JSON only — no prose, no code fences:
{
  "name": "...",
  "relationship": "...",
  "location": "...",
  "how_we_met": "...",
  "background": "...",
  "conversation_style": "...",
  "common_topics": "..."
}

Rules:
- name: as the user said it (original script for names — 보람 stays
  보람, "Sarah" stays "Sarah").
- relationship: a short label naming the type of relationship — the
  ${nativeName} equivalent of "Best friend", "Kita parent", "Senior at
  work", "College roommate". A few words, no more.
- location: 1 short sentence on where they live, work, or spend time.
  Empty string "" if the user didn't say.
- how_we_met: 1 sentence on how they met the user and roughly how
  long they've known each other. Empty string "" if unknown.
- background: 2–3 dense sentences. Shared history, inside jokes, what
  they know about the user, anything specific that would make a
  dialogue feel real. Keep concrete details the user gave — don't
  generalize.
- conversation_style: 1–2 sentences on how they talk — tempo,
  formality, humor, directness, energy.
- common_topics: a short phrase — what the two of them usually end up
  talking about. Empty string "" if unclear.
- Keep the user's own wording where you can. This is a transcription
  into fields, not a rewrite.
- Don't invent facts the user didn't imply. Use empty strings ("")
  rather than fabricating for fields the user didn't touch."""
}
