package com.roro.futurevoice.talk

// GENERATED by scripts/android/gen-path-ideas.py — do not edit.
// Source: FutureVoice/Services/TopicEngine.swift (pathSystemPrompt, seeds),
//         FutureVoice/Views/ScenarioComposerSheet.swift (presets).

object PathIdeasContent {
    class Seed(val title: String, val blurb: String)
    class Category(val title: String, val icon: String)

    /** The composer's preset categories, in the shipped order. */
    val categories: List<Category> = listOf(
        Category("Cafe", "cup.and.saucer.fill"),
        Category("Travel", "airplane"),
        Category("Work", "briefcase.fill"),
        Category("Health", "cross.case.fill"),
        Category("Shopping", "bag.fill"),
        Category("Social", "person.2.fill"),
        Category("School", "graduationcap.fill"),
        Category("Phone", "phone.fill"),
    )

    /** Level 1 of a preset category: shipped, zero round-trip. The sub-areas
     *  of "Cafe" are the same for everyone, and waiting on the model for them
     *  cost the learner the whole pause right after their first tap. */
    val seeds: Map<String, List<Seed>> = mapOf(
        "cafe" to listOf(
            Seed("ordering", "At a cafe: ordering what I actually want, with the changes I want, without pointing at the menu."),
            Seed("paying", "At a cafe: paying at the register when something about the payment doesn't go smoothly."),
            Seed("something's wrong", "At a cafe: my order isn't what I asked for and I want it fixed without making it awkward."),
            Seed("finding a seat", "At a cafe: it's packed and I have to ask about a free seat or share a table with someone."),
            Seed("chatting with staff", "At a cafe: a bit of real small talk with the barista while my drink is being made."),
            Seed("working from here", "At a cafe: asking about the wifi, a plug, or staying a while at my table."),
        ),
        "travel" to listOf(
            Seed("at the airport", "At the airport: check-in, security, or the gate — and a question I need answered fast."),
            Seed("at the hotel", "At the hotel front desk: sorting out my room, my stay, or something that isn't right."),
            Seed("getting around", "Getting around a city I don't know: tickets, directions, and the wrong stop."),
            Seed("eating out abroad", "Eating out in a place where I don't know the menu, the customs, or how ordering works."),
            Seed("border control", "At immigration: answering the officer's questions about my trip, calmly and clearly."),
            Seed("when it goes wrong", "Travel gone wrong: a delay, a lost bag, or a booking that doesn't exist."),
        ),
        "work" to listOf(
            Seed("in a meeting", "In a team meeting: making my point, answering questions, and handling pushback."),
            Seed("with my manager", "A one-on-one with my manager about something I actually need from them."),
            Seed("interviews", "An interview: walking through my experience and why I want this role."),
            Seed("with a client", "A call with a client: setting expectations and handling what they ask for."),
            Seed("small talk at work", "The unplanned work talk — kitchen, hallway, before the meeting starts."),
            Seed("difficult conversations", "At work: raising something uncomfortable with a colleague, professionally."),
        ),
        "health" to listOf(
            Seed("at the doctor", "At the doctor's office: describing what's wrong and answering their questions."),
            Seed("booking an appointment", "Booking a medical appointment and explaining how urgent it is."),
            Seed("at the pharmacy", "At the pharmacy: asking what to take, how to take it, and what's covered."),
            Seed("at the dentist", "At the dentist: describing the pain and understanding what they want to do."),
            Seed("insurance & paperwork", "Sorting out health insurance or a form nobody explains properly."),
            Seed("something urgent", "An urgent health moment where I have to explain the situation fast."),
        ),
        "shopping" to listOf(
            Seed("asking for help", "In a store: asking staff to help me find or choose the right thing."),
            Seed("trying things on", "In a store: sizes, fit, and asking for something different."),
            Seed("returns & refunds", "Returning something and dealing with a clerk who isn't keen to take it back."),
            Seed("at the checkout", "At the checkout: prices, discounts, or something ringing up wrong."),
            Seed("an online order", "An online order that arrived late, wrong, or damaged — and getting it sorted."),
            Seed("at the market", "At a market stall: asking what's good today and buying the right amount."),
        ),
        "social" to listOf(
            Seed("meeting someone new", "Meeting someone for the first time and getting past the opening two minutes."),
            Seed("catching up", "Catching up with someone I haven't seen in a while."),
            Seed("at a party", "At a party where I barely know anyone and have to join a conversation."),
            Seed("making plans", "Making plans with someone: suggesting, negotiating, and pinning down a time."),
            Seed("saying no", "Turning down an invitation or a favor without it getting weird."),
            Seed("something personal", "A conversation about something that actually matters to one of us."),
        ),
        "school" to listOf(
            Seed("in class", "In class: asking a question or saying I didn't follow something."),
            Seed("with a teacher", "Talking to a teacher one-on-one about my work or a problem I have."),
            Seed("group work", "Group work: dividing up the work and dealing with someone not pulling their weight."),
            Seed("admin & enrollment", "At the school office: enrollment, documents, or a deadline I need moved."),
            Seed("exams & deadlines", "Asking about an exam, a grade, or an extension I need."),
            Seed("around campus", "The everyday campus talk — before class, in the hallway, at lunch."),
        ),
        "phone" to listOf(
            Seed("booking something", "On the phone: booking an appointment or a table and confirming the details."),
            Seed("customer service", "On the phone with customer service about a problem they keep not fixing."),
            Seed("a bad connection", "On a call where I can't hear well and have to ask them to repeat things."),
            Seed("leaving a message", "Leaving a clear voicemail with everything they need to call me back."),
            Seed("canceling something", "Calling to cancel a contract or subscription while they talk me out of it."),
            Seed("an official call", "Calling an office, landlord, or utility about something I need resolved."),
        ),
    )

    fun seedSubAreas(category: String): List<Seed>? = seeds[category.lowercase()]

    fun systemPrompt(languageName: String, count: Int, depth: Int,
                     personName: String?, relationship: String): String {
        val relationshipSuffix = if (relationship.isBlank()) "" else " ($relationship)"
        val withPerson = if (personName == null) "" else """
EVERY scenario is WITH $personName$relationshipSuffix —
a real moment the two of them would plausibly share, grounded in
their relationship. The title/blurb should read as being with them
("catch up over coffee", "help $personName move a couch"), NOT a generic
stranger interaction. Write the blurb in the first person about that
shared moment.""".trimIndent()
        val levelGuidance = if (depth <= 1) """The path is just the top CATEGORY. Return $count broad SUB-AREAS
within it — the natural groupings a learner would drill into next.
e.g. Travel → "at the airport", "at the hotel", "getting around",
"eating out abroad", "an emergency", "border / immigration".
These are still buckets, not one specific moment.""".trimIndent() else """The path is already narrowed. Return $count SPECIFIC, concrete
scenarios — each a real moment with a hook, varied across ordinary,
awkward, transactional, and emotional beats. e.g. Travel > hotel →
"room isn't ready", "noisy room at night", "extending my stay",
"a charge I don't recognize", "asking for a late checkout".""".trimIndent()
        return """You help an advanced $languageName learner build a
conversation scenario by drilling down one step at a time.
$withPerson
$levelGuidance

Return STRICT JSON only — no prose, no code fences:
{ "topics": [ { "title": "...", "blurb": "..." } ] }

Rules:
- title: a SHORT chip label, 2–4 words, no trailing punctuation.
- blurb: ONE first-person sentence usable AS the scenario if the learner
  stops here — as specific as the current depth allows. ≤ 160 chars.
- $languageName. Maximize variety; no
  two nearly identical.""".trimIndent()
    }
}
