package com.roro.futurevoice.talk

// GENERATED by scripts/android/gen-shadow-transcribe-prompt.py — do not edit.
// Source: FutureVoice/Services/ShadowTranscriber.swift (prompt).

import com.roro.futurevoice.data.LanguageCatalog

/**
 * What the model is told when it reads a shadowing take.
 *
 * It is never shown the target sentence: it could only copy it, and a word
 * the model supplies is a mark the learner did not earn. Extracted from the
 * Swift source so a take is graded by the same instructions on both
 * platforms.
 */
object ShadowTranscribePrompt {
    fun build(targetLanguage: String): String {
        val target = LanguageCatalog.englishName(targetLanguage)
        return """You transcribe ONE short spoken attempt from a language-learning
SHADOWING exercise: the speaker listened to a model sentence and said
it back. Output STRICT JSON only — no prose, no code fences:
{ "transcript": "..." }

The attached AUDIO is the only source. You are NOT told which sentence
they were copying, and you must not reconstruct one — write the words
that are in the audio.

- "transcript": VERBATIM what the speaker said, in $target.
  Transcribe as a careful listener who does not know the target
  sentence would: every word you can hear, in the order spoken.
- The speaker is a LEARNER. Expect a non-native accent, uneven pace, a
  false start, a word held too long, or a sentence that stops
  half-way. Write what is there. Never complete a sentence, never fix
  grammar or word order, never tidy it up.
- Connected speech swallows short function words — "soak it all in"
  arrives as one run of sound. Those are precisely the words an
  on-device recognizer drops, and the ones you are here to recover.
  Listen through the run and write them.
- If a word came out as a DIFFERENT word, write the word that was
  actually produced, not the one they were reaching for. This
  transcript is scored, so a word you supply that was never spoken is
  a mark the learner did not earn.
- Skip filler sounds (uh, um). Add nothing the audio does not contain.
- If the audio is silent, unintelligible, or not speech, set
  "transcript" to null. Never invent words.""".trimIndent()
    }
}
