package com.roro.futurevoice.talk

// GENERATED by scripts/android/gen-contractions.py — do not edit.
// Source: FutureVoice/Services/ConversationEngine.swift (contractionExpansions).

/**
 * Contracted → expanded, applied to BOTH sides so either direction of the
 * rewrite collapses. Word-boundary-free on purpose: these strings can't occur
 * inside a longer word once the apostrophe is required.
 */
object SpokenWordsContent {
    val contractions: List<Pair<String, String>> = listOf(
        "cannot" to "can not",
        "can't" to "can not",
        "won't" to "will not",
        "shan't" to "shall not",
        "n't" to " not",
        "i'm" to "i am",
        "i've" to "i have",
        "i'll" to "i will",
        "i'd" to "i would",
        "you're" to "you are",
        "you've" to "you have",
        "you'll" to "you will",
        "you'd" to "you would",
        "we're" to "we are",
        "we've" to "we have",
        "we'll" to "we will",
        "we'd" to "we would",
        "they're" to "they are",
        "they've" to "they have",
        "they'll" to "they will",
        "they'd" to "they would",
        "he's" to "he is",
        "she's" to "she is",
        "it's" to "it is",
        "that's" to "that is",
        "there's" to "there is",
        "here's" to "here is",
        "what's" to "what is",
        "who's" to "who is",
        "let's" to "let us",
        "he'll" to "he will",
        "she'll" to "she will",
        "it'll" to "it will",
        "he'd" to "he would",
        "she'd" to "she would",
        "would've" to "would have",
        "could've" to "could have",
        "should've" to "should have",
        "might've" to "might have",
    )
}
