package com.roro.futurevoice.net

// GENERATED by scripts/android/gen-persona-polish.py — do not edit.
// Source: FutureVoice/Services/PersonaParser.swift (systemPrompt()).

/**
 * The polish pass that turns a rambling spoken answer into compact profile
 * text. Same field in, same field out — it drops restarts and filler and
 * keeps every concrete detail.
 *
 * Extracted from the Swift source so the two platforms cannot drift: a
 * retyped prompt polishes the same answer into two different profiles, and
 * the difference only surfaces months later in how the fluent self talks
 * about the learner's life.
 */
object PersonaPolishPrompt {
    const val SYSTEM: String = """While setting up a language-practice app, the user answered profile
questions BY VOICE: what they do (occupation), who is in their daily
life (household), and anything else about themselves (free notes).
Spoken answers may be in their native language, casual, with restarts
or trailing thoughts.

Rewrite each answer as clean, compact English profile text. First
person is implied — phrases like "Solo founder of an AI app for
parents", not "I am a solo founder…".

Return STRICT JSON only — no prose, no code fences:
{
  "occupation": "...",
  "household": "...",
  "free_notes": "..."
}

Rules:
- Keep every concrete detail the user gave; drop only filler,
  restarts, and repetition. Don't invent or generalize.
- Proper names stay in the script the user used (보람 stays 보람).
- 1–2 dense sentences per field, max.
- An empty answer stays an empty string ""."""
}
