package com.roro.futurevoice.data

/**
 * "Likely situations" — the category chain a learner drills into on Watch
 * (cafe → ordering → order came out wrong), whose leaves prefill the
 * composer, always editable.
 *
 * GENERATED by `scripts/android/gen-situation-tree.py` from
 * `FutureVoice/Views/WatchTab.swift`. This is CONTENT, not code: edit the
 * Swift source and re-run, or the two platforms start offering different
 * situations. 5 categories, 13 leaves.
 */
object SituationTree {

    data class Branch(
        val label: String,
        /** SF Symbol name; only meaningful on a top-level entry. */
        val icon: String? = null,
        val children: List<Branch> = emptyList(),
        /** Set on leaves: the assembled, ready-to-edit situation. */
        val situation: String? = null,
    )

    val roots: List<Branch> = listOf(
        Branch(
            label = "Cafe",
            icon = "cup.and.saucer.fill",
            children = listOf(
                Branch(
                    label = "Ordering",
                    children = listOf(
                        Branch(
                            label = "Order came out wrong",
                            situation = "At a cafe: my order came out wrong, and I want to point it out politely and get it fixed.",
                        ),
                        Branch(
                            label = "Asking for a recommendation",
                            situation = "At a cafe: I can't decide, so I ask the barista what they'd recommend and chat a little.",
                        ),
                        Branch(
                            label = "Complicated custom order",
                            situation = "At a cafe: ordering a drink with several modifications, and the barista has follow-up questions.",
                        )
                    ),
                ),
                Branch(
                    label = "Paying",
                    children = listOf(
                        Branch(
                            label = "Card declined",
                            situation = "At a cafe: my card gets declined at the register and I sort it out without holding up the line.",
                        )
                    ),
                )
            ),
        ),
        Branch(
            label = "Travel",
            icon = "airplane",
            children = listOf(
                Branch(
                    label = "Immigration control",
                    children = listOf(
                        Branch(
                            label = "Purpose-of-visit questions",
                            situation = "At immigration control: the officer asks why I'm visiting, how long I'm staying, and where.",
                        ),
                        Branch(
                            label = "Problem with my documents",
                            situation = "At immigration control: something's off with my documents and I explain calmly.",
                        )
                    ),
                ),
                Branch(
                    label = "Hotel",
                    children = listOf(
                        Branch(
                            label = "Room isn't ready",
                            situation = "Hotel front desk: I arrive early, the room isn't ready, and I negotiate my options.",
                        ),
                        Branch(
                            label = "Something's wrong with the room",
                            situation = "Hotel front desk: the room has a problem and I ask to have it fixed or changed.",
                        )
                    ),
                )
            ),
        ),
        Branch(
            label = "Work",
            icon = "briefcase.fill",
            children = listOf(
                Branch(
                    label = "Interview",
                    children = listOf(
                        Branch(
                            label = "Job interview",
                            situation = "A job interview: introducing myself, walking through my experience, and why I want this role.",
                        )
                    ),
                ),
                Branch(
                    label = "Meeting",
                    children = listOf(
                        Branch(
                            label = "Presenting my idea",
                            situation = "A team meeting: I present my idea, field questions, and handle pushback.",
                        )
                    ),
                ),
                Branch(
                    label = "With my manager",
                    children = listOf(
                        Branch(
                            label = "Asking for time off",
                            situation = "A one-on-one with my manager: asking for time off next month and handling their concerns.",
                        )
                    ),
                )
            ),
        ),
        Branch(
            label = "Health",
            icon = "cross.case.fill",
            children = listOf(
                Branch(
                    label = "Doctor's visit",
                    children = listOf(
                        Branch(
                            label = "Describing a symptom",
                            situation = "At the doctor's office: describing a symptom I've had for a week and answering their questions.",
                        )
                    ),
                )
            ),
        ),
        Branch(
            label = "Shopping",
            icon = "bag.fill",
            children = listOf(
                Branch(
                    label = "Returns",
                    children = listOf(
                        Branch(
                            label = "No receipt",
                            situation = "At a store: returning an item without the receipt, and the clerk is skeptical.",
                        )
                    ),
                )
            ),
        ),
    )

    /**
     * Categories matching the persona's "when do you most need it" picks
     * first, tree order within each group. The onboarding chips are the whole
     * point of asking — this is where they visibly pay off.
     */
    fun prioritized(situations: List<String>): List<Branch> {
        if (situations.isEmpty()) return roots
        val wanted = situations.flatMap { labels(it) }.toSet()
        if (wanted.isEmpty()) return roots
        return roots.filter { it.label in wanted } + roots.filterNot { it.label in wanted }
    }

    /**
     * One persona situation → category labels. Presets map explicitly; free
     * text matches a category when its label appears in what they wrote.
     */
    private fun labels(situation: String): List<String> {
        PRESETS[situation]?.let { return it }
        val lowered = situation.lowercase()
        return roots.map { it.label }.filter { lowered.contains(it.lowercase()) }
    }

    private val PRESETS = mapOf(
        "Work meetings" to listOf("Work"),
        "Client calls" to listOf("Work"),
        "Doctor / clinic" to listOf("Health"),
        "Travel" to listOf("Travel"),
        "Online shopping" to listOf("Shopping"),
        "Customer service" to listOf("Shopping"),
        "Daily small talk" to listOf("Cafe"),
    )
}
