package com.roro.futurevoice.data

// GENERATED by scripts/android/gen-voice-accents.py — do not edit.
// Source: FutureVoice/Services/VoiceAccent.swift

/**
 * A selectable output accent for the cloned voice, applied AFTER cloning via
 * ElevenLabs voice remixing (`elevenlabs-voice-remix`).
 *
 * Exists because a clone recorded in the learner's NATIVE language carries no
 * target-language accent information at all — the TTS model fills that gap
 * with its own default (US English for `en`), which is wrong for, say, a
 * learner living in London. Remixing keeps the person and changes only the
 * accent; the learner auditions a few takes and keeps one.
 */
data class VoiceAccent(
    /** Target language this option belongs to. */
    val language: String,
    /** Stable id, reported to analytics ("en-GB"). */
    val id: String,
    /** Row label. */
    val label: String,
    /** The remix instruction sent upstream as `voice_description`. */
    val prompt: String,
)

object VoiceAccentCatalog {

    /**
     * One shared shape so every option pulls equally hard toward "same
     * person, different accent" — the remix must never drift into a new
     * character, because speaker similarity is the product.
     */
    /**
     * How far the remix may drift from the reference audio (upstream
     * `prompt_strength`: 0 keeps almost everything of the recording, 1 keeps
     * almost nothing). The prompt ASKS for the same person; this is what
     * decides it. Low on purpose: an accent that sounds like someone else is
     * worse than no accent. Chosen by ear with
     * `scripts/voice-remix-probe.sh` — retune there, never by feel.
     */
    const val PROMPT_STRENGTH: Double = 0.3

    private fun prompt(accent: String) = "Keep this exact same voice: the same person, timbre, pitch, age and character. Change ONLY the accent — the speaker now has a natural, consistent %s. Do not change anything else about how the voice sounds.".format(accent)

    private val all = listOf(
        VoiceAccent("en", "en-US", "American", prompt("General American English accent")),
        VoiceAccent("en", "en-GB", "British", prompt("British English accent with standard Southern British pronunciation")),
        VoiceAccent("en", "en-AU", "Australian", prompt("Australian English accent")),
        VoiceAccent("de", "de-DE", "Standard German", prompt("Standard German accent (Hochdeutsch) as spoken in Germany")),
    )

    /** Accent choices for a target language. Empty = the picker never shows
     *  for that language; v1 ships English only. */
    fun options(language: String): List<VoiceAccent> =
        all.filter { it.language == language.take(2) }

    /**
     * The accent every new clone is remixed into — the FIRST option of the
     * language (iOS `VoiceAccentCatalog.defaultAccent(for:)`, 2026-10-08).
     * Null = no remix for this language.
     */
    fun defaultAccent(language: String): VoiceAccent? = options(language).firstOrNull()

    private val samples = mapOf(
        "en" to "I'll grab a bottle of water and a coffee around half past eight. I can't be late again, the bus leaves at nine, doesn't it?",
        "de" to "Morgen früh hole ich zwei Brötchen beim Bäcker, danach fahre ich mit dem Zug nach München. Ich rufe dich später an, okay?",
    )

    /**
     * The line the remix previews speak (ElevenLabs wants 100–1000 chars).
     * Written to surface accent-revealing sounds — for English: t-flapping
     * ("water", "better"), the bath/trap split ("can't", "half past"),
     * rhoticity ("park", "there"), and a tag question's intonation.
     */
    fun sampleText(language: String): String =
        samples[language.take(2)] ?: samples["en"]!!
}
