package com.roro.futurevoice.data

// GENERATED by scripts/android/gen-voice-accents.py — do not edit.
// Source: FutureVoice/Services/VoiceAccent.swift

/**
 * A selectable output accent for the cloned voice, applied AFTER cloning via
 * ElevenLabs voice remixing (`elevenlabs-voice-remix`).
 *
 * Exists because a clone recorded in the learner's NATIVE language carries no
 * target-language accent information at all — the TTS model fills that gap
 * with its own default (US English for `en`), which is wrong for, say, a
 * learner living in London. Remixing keeps the person and changes only the
 * accent; the learner auditions a few takes and keeps one.
 */
data class VoiceAccent(
    /** Target language this option belongs to. */
    val language: String,
    /** Stable id, reported to analytics ("en-GB"). */
    val id: String,
    /** Row label. */
    val label: String,
    /** The remix instruction sent upstream as `voice_description`. */
    val prompt: String,
)

object VoiceAccentCatalog {

    /**
     * One shared shape so every option pulls equally hard toward "same
     * person, different accent" — the remix must never drift into a new
     * character, because speaker similarity is the product.
     */
    private fun prompt(accent: String) = "Keep this exact same voice: the same person, timbre, pitch, age and character. Change ONLY the accent — the speaker now has a natural, consistent %s. Do not change anything else about how the voice sounds.".format(accent)

    private val all = listOf(
        VoiceAccent("en", "en-US", "American", prompt("General American English accent")),
        VoiceAccent("en", "en-GB", "British", prompt("British English accent with standard Southern British pronunciation")),
        VoiceAccent("en", "en-AU", "Australian", prompt("Australian English accent")),
    )

    /** Accent choices for a target language. Empty = the picker never shows
     *  for that language; v1 ships English only. */
    fun options(language: String): List<VoiceAccent> =
        all.filter { it.language == language.take(2) }

    private val samples = mapOf(
        "en" to "Right — let me think about tomorrow. I'll grab a bottle of water and a cup of coffee on the way, probably around half past eight. I can't be late again; the last bus leaves at twenty to nine. Honestly, the weather's been better lately, hasn't it? Maybe I'll walk through the park instead, and I'll call you when I get there.",
    )

    /**
     * The line the remix previews speak (ElevenLabs wants 100–1000 chars).
     * Written to surface accent-revealing sounds — for English: t-flapping
     * ("water", "better"), the bath/trap split ("can't", "half past"),
     * rhoticity ("park", "there"), and a tag question's intonation.
     */
    fun sampleText(language: String): String =
        samples[language.take(2)] ?: samples["en"]!!
}
