// Shared dictionary lookup — cache-or-generate, FREE (no credit charge).
//
// Body: { word, native_lang, target_lang?, kind? }
//       kind: "word" (default) | "expression"
// Returns: { data: WordEntry } (200) — the same structured entry the client's
//          WordCard / ExpressionCard renders, whether it came from the shared
//          cache or a fresh generation.
//
// TWO prompts, not one. A word gets a headword treatment (senses by part of
// speech). An expression gets a chunk treatment: what the WHOLE phrase means,
// when you reach for it, and examples that contain it verbatim. Sending a
// phrase through the word prompt is what produced "hundred active users" →
// the dictionary entry for "hundred" (see 20260813140000_word_entry_expressions).
//
// Neither prompt names a language: both are written from `target_lang`, so
// this serves any target the app enrolls without a code change.
//
// Why this is its own function instead of a "free purpose" on `gemini`:
// the prompts here are fixed server-side, so a user CAN'T tag arbitrary
// generations (conversation turns, summaries) as "word" to dodge charges.
// The only abuse surface is spamming brand-new entries to run up generation
// cost + junk the shared cache — capped by a per-user hourly generation limit.
//
// word_entry is a global cache keyed by (word, native_lang, target_lang, kind)
// and readable by everyone, so an entry generated by ANY user is free for
// every other user forever. That's why lookups aren't credit-gated.

import "jsr:@supabase/functions-js/edge-runtime.d.ts"
import { requireUser, handlePreflight, errorResponse, cors } from "../_shared/auth.ts"
import { serviceRoleClient } from "../_shared/credits.ts"

// Legit learners hit a handful of NEW (uncached) words per session and quickly
// converge to cache hits as the shared dictionary warms. This cap only bites
// on someone generating brand-new words en masse; cache hits are unlimited.
const MAX_NEW_GENERATIONS_PER_HOUR = 150
// A word key is a short lemma; an expression is a 2–6 word chunk, which the
// 40-char word ceiling silently rejected (400 → the card rendered "—").
const MAX_LEN: Record<Kind, number> = { word: 40, expression: 80 }

type Kind = "word" | "expression"

Deno.serve(async (req) => {
  const pre = handlePreflight(req)
  if (pre) return pre
  if (req.method !== "POST") return errorResponse(405, "method not allowed")

  const authed = await requireUser(req)
  if (authed instanceof Response) return authed
  const { user } = authed

  let body: { word?: string; native_lang?: string; target_lang?: string; kind?: string }
  try { body = await req.json() } catch { return errorResponse(400, "invalid json body") }

  const word = (body.word ?? "").trim()
  const native = (body.native_lang ?? "").trim()
  // Older clients send no target — they were all English-target word lookups,
  // which is exactly what the legacy rows are stamped with.
  const target = (body.target_lang ?? "").trim() || "en"
  const kind: Kind = body.kind === "expression" ? "expression" : "word"
  if (!word || !native) return errorResponse(400, "word and native_lang required")
  // Both codes are interpolated into the generation prompt AND the result is
  // published to a cache every user reads, so they have to be language tags
  // and nothing else.
  if (!isLanguageTag(native) || !isLanguageTag(target)) {
    return errorResponse(400, "native_lang and target_lang must be language codes")
  }
  // Reject anything past the key's shape — it's a prompt-injection attempt to
  // coax long free-form generation, not a headword.
  if (word.length > MAX_LEN[kind]) return errorResponse(400, "word too long")

  const svc = serviceRoleClient()

  // 1. Shared cache — the overwhelmingly common path once warm. Free.
  {
    const { data, error } = await svc
      .from("word_entry")
      .select("data")
      .eq("word", word).eq("native_lang", native)
      .eq("target_lang", target).eq("kind", kind)
      .limit(1).maybeSingle()
    if (error) return errorResponse(500, "cache read failed", error.message)
    if (data) return json({ data: data.data })
  }

  // 2. Cache miss → generation. Rate-limit NEW generations per user so the
  //    free path can't be turned into a cost/pollution firehose.
  {
    const since = new Date(Date.now() - 60 * 60 * 1000).toISOString()
    const { count, error } = await svc
      .from("word_entry")
      .select("word", { count: "exact", head: true })
      .eq("created_by", user.id)
      .gte("created_at", since)
    if (error) return errorResponse(500, "rate check failed", error.message)
    if ((count ?? 0) >= MAX_NEW_GENERATIONS_PER_HOUR) {
      return errorResponse(429, "too many new words this hour")
    }
  }

  // 3. Generate with the FIXED prompt, then publish for everyone.
  const apiKey = Deno.env.get("GEMINI_API_KEY")
  if (!apiKey) return errorResponse(500, "server missing GEMINI_API_KEY")

  const entry = await generate(word, native, target, kind, apiKey)
  if (!entry) return errorResponse(502, "generation failed")

  // Upsert (not insert): a concurrent request for the same word may have won
  // the race — onConflict keeps it idempotent instead of erroring.
  const { error: upErr } = await svc
    .from("word_entry")
    .upsert({ word, native_lang: native, target_lang: target, kind,
              data: entry, created_by: user.id },
            { onConflict: "word,native_lang,target_lang,kind" })
  if (upErr) {
    // The entry is still valid even if caching failed — return it, just
    // uncached (next lookup will regenerate). Don't fail the user's request.
    console.error("word_entry upsert failed (non-fatal)", upErr.message)
  }

  return json({ data: entry })
})

function json(payload: unknown, status = 200): Response {
  return new Response(JSON.stringify(payload), {
    status,
    headers: { "Content-Type": "application/json", ...cors() },
  })
}

// BCP-47 shape: "ko", "pt-BR", "zh-Hans-CN". Deliberately narrow.
function isLanguageTag(code: string): boolean {
  return /^[a-zA-Z]{2,3}(-[a-zA-Z0-9]{2,8}){0,3}$/.test(code)
}

function languageName(code: string): string {
  try {
    return new Intl.DisplayNames(["en"], { type: "language" }).of(code) ?? code
  } catch {
    return code
  }
}

// The headword treatment: senses grouped by part of speech. Unchanged in
// shape from the original client-side prompt (entries generated before this
// function still render identically) — only the hardcoded "English" is gone.
function wordPrompt(target: string, native: string): string {
  const t = languageName(target), n = languageName(native)
  return `You are a bilingual learner's dictionary. For the ${t} word the user sends, \
return a JSON object explaining it for a native ${n} speaker. Write every \
meaning, note and phrase-meaning in ${n} — never transliterate the ${t} \
word (explain it, don't respell it in the ${n} script).

JSON shape (no markdown, JSON only):
{
  "pos": "<short part-of-speech summary in ${n}>",
  "senses": [
    { "pos": "<part of speech in ${n}>", "meaning": "<gloss in ${n}>", "note": "<short usage nuance in ${n}, or null>" }
  ],
  "examples": [
    { "text": "<short, natural SPOKEN ${t} sentence using the word>", "meaning": "<that sentence translated into ${n}>" }
  ],
  "phrases": [
    { "phrase": "<common ${t} idiom/collocation with the word>", "meaning": "<its meaning in ${n}>" }
  ],
  "properNoun": "<one line in ${n} if the capitalized word is also a well-known name/brand, else null>"
}

Cover the distinct common senses. Give as many examples as the word genuinely \
warrants — a simple one-sense word may need a single example, a word with \
several senses may want one example per sense. Don't pad; don't force a count. \
Include only genuinely common phrases (none is fine). Keep everything concise.`
}

// The chunk treatment. An expression has no headword to look up, so the ONE
// rule that matters is: explain the phrase the user sent, whole, and never
// fall back to glossing a word inside it. The JSON shape is deliberately the
// same as a word's (the client decodes one WordEntry either way) with the
// fields repurposed — senses carry the phrase's meaning + when to use it,
// phrases carry near-variants.
function expressionPrompt(target: string, native: string): string {
  const t = languageName(target), n = languageName(native)
  return `You explain ${t} EXPRESSIONS to a native ${n} speaker who is learning ${t}. \
The user sends a multi-word chunk — a collocation, a softener, a fixed phrase, \
or just a phrase that came up in their practice.

THE RULE THAT OVERRIDES EVERYTHING: explain the chunk AS A WHOLE. Never \
produce a dictionary entry for one word inside it. If the user sends "that \
covers everything", you explain what saying that phrase DOES ("that's \
everything, we're done here") — you do NOT define the word "that". If the \
chunk is transparent and not idiomatic (e.g. an ordinary noun phrase like \
"a hundred active users"), say plainly what it refers to and how it is used \
in speech; do not invent idiomatic meaning it doesn't have.

Write every meaning and note in ${n}. Keep every example in ${t}.

JSON shape (no markdown, JSON only):
{
  "pos": "<2-4 words in ${n} naming what kind of chunk this is and its register, e.g. 구어체 관용 표현>",
  "senses": [
    { "pos": "", "meaning": "<what the WHOLE chunk means, in ${n}>", "note": "<when you reach for it and the tone it carries, in ${n}, or null>" }
  ],
  "examples": [
    { "text": "<natural SPOKEN ${t} sentence CONTAINING THE CHUNK VERBATIM>", "meaning": "<that sentence translated into ${n}>" }
  ],
  "phrases": [
    { "phrase": "<${t} phrase that makes the same move, for when this one doesn't fit>", "meaning": "<its meaning/nuance difference in ${n}>" }
  ],
  "properNoun": null
}

Usually ONE sense — add a second only if the chunk genuinely does two \
different jobs. 2-3 examples, each a different situation, and each must \
contain the chunk word-for-word as sent. 0-2 variants; none is fine. \
Keep everything concise.`
}

async function generate(
  word: string, native: string, target: string, kind: Kind, apiKey: string,
): Promise<unknown | null> {
  const system = kind === "expression"
    ? expressionPrompt(target, native)
    : wordPrompt(target, native)

  try {
    const upstream = await fetch(
      `https://generativelanguage.googleapis.com/v1beta/models/gemini-3.6-flash:generateContent?key=${apiKey}`,
      {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          system_instruction: { parts: [{ text: system }] },
          contents: [{ role: "user", parts: [{ text: word }] }],
          generationConfig: {
            // No temperature: gen-3 models degrade on sub-1.0 sampling, same
            // reason GeminiClient drops it for the flash-3 family.
            maxOutputTokens: 900,
            thinkingConfig: { thinkingLevel: "low" },
            responseMimeType: "application/json",
          },
        }),
      },
    )
    if (!upstream.ok) {
      console.error("gemini upstream error", upstream.status, (await upstream.text()).slice(0, 300))
      return null
    }
    const payload = await upstream.json()
    const text: string = payload?.candidates?.[0]?.content?.parts
      ?.map((p: { text?: string }) => p.text ?? "").join("") ?? ""
    const start = text.indexOf("{"), end = text.lastIndexOf("}")
    if (start < 0 || end < start) return null
    return JSON.parse(text.slice(start, end + 1))
  } catch (e) {
    console.error("word-entry generate failed", e)
    return null
  }
}
