// Shared word-dictionary lookup — cache-or-generate, FREE (no credit charge).
//
// Body: { word: string, native_lang: string }
// Returns: { data: WordEntry } (200) — the same structured entry the client's
//          WordCard renders, whether it came from the shared cache or a fresh
//          generation.
//
// Why this is its own function instead of a "free purpose" on `gemini`:
// the prompt here is fixed server-side, so a user CAN'T tag arbitrary
// generations (conversation turns, summaries) as "word" to dodge charges.
// The only abuse surface is spamming brand-new words to run up generation
// cost + junk the shared cache — capped by a per-user hourly generation limit.
//
// word_entry is a global cache keyed by (word, native_lang) and readable by
// everyone, so a word generated by ANY user is free for every other user
// forever. That's why lookups aren't credit-gated.

import "jsr:@supabase/functions-js/edge-runtime.d.ts"
import { requireUser, handlePreflight, errorResponse, cors } from "../_shared/auth.ts"
import { serviceRoleClient } from "../_shared/credits.ts"

// Legit learners hit a handful of NEW (uncached) words per session and quickly
// converge to cache hits as the shared dictionary warms. This cap only bites
// on someone generating brand-new words en masse; cache hits are unlimited.
const MAX_NEW_GENERATIONS_PER_HOUR = 150
const MAX_WORD_LEN = 40

Deno.serve(async (req) => {
  const pre = handlePreflight(req)
  if (pre) return pre
  if (req.method !== "POST") return errorResponse(405, "method not allowed")

  const authed = await requireUser(req)
  if (authed instanceof Response) return authed
  const { user } = authed

  let body: { word?: string; native_lang?: string }
  try { body = await req.json() } catch { return errorResponse(400, "invalid json body") }

  const word = (body.word ?? "").trim()
  const native = (body.native_lang ?? "").trim()
  if (!word || !native) return errorResponse(400, "word and native_lang required")
  // A dictionary key is a single word/short lemma — reject anything that looks
  // like a prompt-injection attempt to coax long free-form generation.
  if (word.length > MAX_WORD_LEN) return errorResponse(400, "word too long")

  const svc = serviceRoleClient()

  // 1. Shared cache — the overwhelmingly common path once warm. Free.
  {
    const { data, error } = await svc
      .from("word_entry")
      .select("data")
      .eq("word", word).eq("native_lang", native)
      .limit(1).maybeSingle()
    if (error) return errorResponse(500, "cache read failed", error.message)
    if (data) return json({ data: data.data })
  }

  // 2. Cache miss → generation. Rate-limit NEW generations per user so the
  //    free path can't be turned into a cost/pollution firehose.
  {
    const since = new Date(Date.now() - 60 * 60 * 1000).toISOString()
    const { count, error } = await svc
      .from("word_entry")
      .select("word", { count: "exact", head: true })
      .eq("created_by", user.id)
      .gte("created_at", since)
    if (error) return errorResponse(500, "rate check failed", error.message)
    if ((count ?? 0) >= MAX_NEW_GENERATIONS_PER_HOUR) {
      return errorResponse(429, "too many new words this hour")
    }
  }

  // 3. Generate with the FIXED prompt, then publish for everyone.
  const apiKey = Deno.env.get("GEMINI_API_KEY")
  if (!apiKey) return errorResponse(500, "server missing GEMINI_API_KEY")

  const entry = await generate(word, native, apiKey)
  if (!entry) return errorResponse(502, "generation failed")

  // Upsert (not insert): a concurrent request for the same word may have won
  // the race — onConflict keeps it idempotent instead of erroring.
  const { error: upErr } = await svc
    .from("word_entry")
    .upsert({ word, native_lang: native, data: entry, created_by: user.id },
            { onConflict: "word,native_lang" })
  if (upErr) {
    // The entry is still valid even if caching failed — return it, just
    // uncached (next lookup will regenerate). Don't fail the user's request.
    console.error("word_entry upsert failed (non-fatal)", upErr.message)
  }

  return json({ data: entry })
})

function json(payload: unknown, status = 200): Response {
  return new Response(JSON.stringify(payload), {
    status,
    headers: { "Content-Type": "application/json", ...cors() },
  })
}

// Mirrors the (now-removed) client-side WordLore.generate prompt verbatim so
// entries look identical whether they predate this function or not.
async function generate(word: string, native: string, apiKey: string): Promise<unknown | null> {
  const lang = new Intl.DisplayNames(["en"], { type: "language" }).of(native) ?? native
  const system = `You are a bilingual learner's dictionary. For the English word the user sends, \
return a JSON object explaining it for a native ${lang} speaker. Write every \
meaning, note and phrase-meaning in ${lang} — never transliterate the English \
word (e.g. "slack" must be explained, NOT written "슬랙").

JSON shape (no markdown, JSON only):
{
  "pos": "<short part-of-speech summary in ${lang}, e.g. 형용사·명사·동사>",
  "senses": [
    { "pos": "<part of speech in ${lang}>", "meaning": "<gloss in ${lang}>", "note": "<short usage nuance in ${lang}, or null>" }
  ],
  "examples": [
    { "text": "<short, natural SPOKEN English sentence using the word>", "meaning": "<that sentence translated into ${lang}>" }
  ],
  "phrases": [
    { "phrase": "<common English idiom/collocation with the word>", "meaning": "<its meaning in ${lang}>" }
  ],
  "properNoun": "<one line in ${lang} if the capitalized word is also a well-known name/brand, else null>"
}

Cover the distinct common senses. Give as many examples as the word genuinely \
warrants — a simple one-sense word may need a single example, a word with \
several senses may want one example per sense. Don't pad; don't force a count. \
Include only genuinely common phrases (none is fine). Keep everything concise.`

  try {
    const upstream = await fetch(
      `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=${apiKey}`,
      {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          system_instruction: { parts: [{ text: system }] },
          contents: [{ role: "user", parts: [{ text: word }] }],
          generationConfig: {
            temperature: 0.3,
            maxOutputTokens: 700,
            thinkingConfig: { thinkingBudget: 0 },
            responseMimeType: "application/json",
          },
        }),
      },
    )
    if (!upstream.ok) {
      console.error("gemini upstream error", upstream.status, (await upstream.text()).slice(0, 300))
      return null
    }
    const payload = await upstream.json()
    const text: string = payload?.candidates?.[0]?.content?.parts
      ?.map((p: { text?: string }) => p.text ?? "").join("") ?? ""
    const start = text.indexOf("{"), end = text.lastIndexOf("}")
    if (start < 0 || end < start) return null
    return JSON.parse(text.slice(start, end + 1))
  } catch (e) {
    console.error("word-entry generate failed", e)
    return null
  }
}
