// Platform news pool.
//
// Body: { categories: string[], language?: string, refresh?: boolean }
// Returns: { topics: [{ category, title, blurb }] }
//
// Each (category, language, day) batch is generated by Gemini + Google
// Search AT MOST ONCE platform-wide — the first request of the day for a
// category pays the upstream cost (on the platform's key), everyone else
// reads the cached row. Users are NOT charged credits for this: it's
// shared editorial content, not per-user generation.
//
// refresh=true asks for MORE stories: categories whose pool hasn't hit the
// daily cap get one extra batch appended to the same row (prompt excludes
// already-fetched titles). The cap bounds platform cost no matter how often
// users hammer the refresh button.

import "jsr:@supabase/functions-js/edge-runtime.d.ts"
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.45.0"
import { requireUser, handlePreflight, errorResponse, cors } from "../_shared/auth.ts"

const MAX_CATEGORIES = 6
const TOPICS_PER_CATEGORY = 3
// Daily platform-wide ceiling per (category, language): 3 batches = 9 topics.
const MAX_TOPICS_PER_DAY = TOPICS_PER_CATEGORY * 3

Deno.serve(async (req) => {
  const pre = handlePreflight(req)
  if (pre) return pre
  if (req.method !== "POST") return errorResponse(405, "method not allowed")

  const authed = await requireUser(req)
  if (authed instanceof Response) return authed

  let body: { categories?: unknown; language?: unknown; refresh?: unknown }
  try { body = await req.json() } catch { return errorResponse(400, "invalid json body") }
  const wantsMore = body.refresh === true

  const language = typeof body.language === "string" && body.language.trim()
    ? body.language.trim().toLowerCase()
    : "en"
  const categories = normalizeCategories(body.categories)
  if (categories.length === 0) {
    return jsonResponse({ topics: [] })
  }

  // Service-role client — news_topics has no user write policies.
  const service = createClient(
    Deno.env.get("SUPABASE_URL")!,
    Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,
  )
  const today = new Date().toISOString().slice(0, 10)

  const { data: existing } = await service
    .from("news_topics")
    .select("category")
    .eq("language", language)
    .eq("fetched_date", today)
    .in("category", categories)

  const have = new Set((existing ?? []).map((r: { category: string }) => r.category))
  const missing = categories.filter((c) => !have.has(c))

  const apiKey = Deno.env.get("GEMINI_API_KEY")
  if (missing.length > 0 && apiKey) {
    // Parallel per-category generation; a failed category is skipped rather
    // than failing the whole request. ignoreDuplicates makes concurrent
    // first-requests race-safe — one row wins, the rest no-op.
    await Promise.all(missing.map(async (category) => {
      try {
        const topics = await generateTopics(category, language, apiKey)
        if (topics.length > 0) {
          await service.from("news_topics").upsert(
            { category, language, fetched_date: today, topics },
            { onConflict: "category,language,fetched_date", ignoreDuplicates: true },
          )
        }
      } catch (_err) {
        // skip — category simply won't appear today
      }
    }))
  }

  // Refresh: grow each category's pool by one more batch, capped per day.
  // The prompt excludes titles already in the pool so the new batch covers
  // DIFFERENT stories. Read-modify-write; a concurrent-refresh race at worst
  // appends a duplicate title, which the response dedupe below absorbs.
  if (wantsMore && apiKey) {
    const { data: growRows } = await service
      .from("news_topics")
      .select("id,category,topics")
      .eq("language", language)
      .eq("fetched_date", today)
      .in("category", categories)
    await Promise.all((growRows ?? []).map(async (row) => {
      const existing = (row.topics ?? []) as { title: string; blurb: string }[]
      if (existing.length >= MAX_TOPICS_PER_DAY) return
      try {
        const fresh = await generateTopics(
          row.category, language, apiKey, existing.map((t) => t.title))
        const known = new Set(existing.map((t) => t.title.toLowerCase()))
        const add = fresh.filter((t) => !known.has(t.title.toLowerCase()))
        if (add.length > 0) {
          await service.from("news_topics")
            .update({ topics: [...existing, ...add] })
            .eq("id", row.id)
        }
      } catch (_err) {
        // skip — category keeps its current pool
      }
    }))
  }

  const { data: rows, error } = await service
    .from("news_topics")
    .select("category,topics")
    .eq("language", language)
    .eq("fetched_date", today)
    .in("category", categories)
  if (error) return errorResponse(500, "read failed", error.message)

  const out: { category: string; title: string; blurb: string; facts: string[] }[] = []
  const seenTitles = new Set<string>()
  for (const row of rows ?? []) {
    for (const t of row.topics as { title: string; blurb: string; facts?: string[] }[]) {
      if (!t?.title) continue
      const key = `${row.category}|${t.title.toLowerCase()}`
      if (seenTitles.has(key)) continue
      seenTitles.add(key)
      out.push({
        category: row.category, title: t.title, blurb: t.blurb ?? "",
        // Rows cached before the facts field existed simply send [] — the
        // client falls back to the blurb.
        facts: Array.isArray(t.facts) ? t.facts : [],
      })
    }
  }
  return jsonResponse({ topics: out })
})

function normalizeCategories(raw: unknown): string[] {
  if (!Array.isArray(raw)) return []
  const seen = new Set<string>()
  const out: string[] = []
  for (const item of raw) {
    if (typeof item !== "string") continue
    const norm = item.trim().toLowerCase()
    if (!norm || norm.length > 60 || seen.has(norm)) continue
    seen.add(norm)
    out.push(norm)
    if (out.length >= MAX_CATEGORIES) break
  }
  return out
}

async function generateTopics(
  category: string,
  language: string,
  apiKey: string,
  avoidTitles: string[] = [],
): Promise<{ title: string; blurb: string; facts: string[] }[]> {
  const today = new Date().toISOString().slice(0, 10)
  const avoidBlock = avoidTitles.length === 0 ? "" :
    `\n\nAlready covered today — find DIFFERENT stories, do not repeat these:\n` +
    avoidTitles.map((t) => `- ${t}`).join("\n")
  const system =
    `Use Google Search to find ${TOPICS_PER_CATEGORY} recent news stories ` +
    `(published within the last 7 days, each from a different story) about: ${category}. ` +
    `They will be used as conversation-practice topics for ${language} learners.\n\n` +
    `Return STRICT JSON only — no prose, no code fences:\n` +
    `{ "topics": [ { "title": "...", "blurb": "...", "facts": ["...", "..."] } ] }\n\n` +
    `- title: how a friend would bring the story up in ${language}, ` +
    `10 words or fewer ("Did you see the news about ..." energy, not a headline).\n` +
    `- blurb: 1-2 sentences of plain facts from the search results — what ` +
    `happened, who, when. Nothing that isn't in the sources: no speculation, ` +
    `no color, no invented details.\n` +
    `- facts: 5-7 short plain-language facts from the coverage — what ` +
    `happened, who, when, key numbers, notable reactions. Each ≤ 20 words, ` +
    `in ${language}. Facts only, nothing invented; these ground a whole ` +
    `conversation about the story, so cover its distinct angles.` + avoidBlock

  // gemini-3.6-flash: the 2.5 family retires 2026-10-16. Gen-3 takes
  // thinkingLevel (not thinkingBudget) and prefers default sampling — no
  // temperature (mirrors the app's GeminiClient).
  const upstream = await fetch(
    `https://generativelanguage.googleapis.com/v1beta/models/gemini-3.6-flash:generateContent?key=${apiKey}`,
    {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        system_instruction: { parts: [{ text: system }] },
        contents: [{ role: "user", parts: [{ text: `Today is ${today}.` }] }],
        tools: [{ google_search: {} }],
        generationConfig: {
          // Room for 3 topics × (title + blurb + 5-7 facts).
          maxOutputTokens: 2200,
          thinkingConfig: { thinkingLevel: "low" },
        },
      }),
    },
  )
  if (!upstream.ok) throw new Error(`gemini ${upstream.status}`)

  const data = await upstream.json()
  const text: string = (data?.candidates?.[0]?.content?.parts ?? [])
    .map((p: { text?: string }) => p.text ?? "")
    .join("")
  const start = text.indexOf("{")
  const end = text.lastIndexOf("}")
  if (start < 0 || end <= start) return []
  const parsed = JSON.parse(text.slice(start, end + 1))
  const topics = Array.isArray(parsed?.topics) ? parsed.topics : []
  return topics
    .filter((t: { title?: string }) => typeof t?.title === "string" && t.title.trim())
    .slice(0, TOPICS_PER_CATEGORY)
    .map((t: { title: string; blurb?: string; facts?: unknown }) => ({
      title: t.title.trim(),
      blurb: (t.blurb ?? "").trim(),
      facts: Array.isArray(t.facts)
        ? t.facts.filter((f: unknown) => typeof f === "string" && f.trim()).slice(0, 8)
        : [],
    }))
}

function jsonResponse(payload: unknown): Response {
  return new Response(JSON.stringify(payload), {
    status: 200,
    headers: { "Content-Type": "application/json", ...cors() },
  })
}
