-- A full, rich dictionary entry for one word, generated by Gemini in ONE call
-- and shared by every user (per native language). Replaces the thin
-- word_lore (example only) + word_meaning (single-line translate) pair, which
-- transliterated words like "slack" → "슬랙" instead of explaining them.
--
-- `data` holds the structured entry (senses by part of speech, an example with
-- its native translation, common phrases/idioms, an optional proper-noun note).

create table if not exists public.word_entry (
  word         text not null,
  native_lang  text not null,        -- BCP-47 of the reader, e.g. 'ko'
  data         jsonb not null,
  created_at   timestamptz not null default now(),
  primary key (word, native_lang)
);

alter table public.word_entry enable row level security;

drop policy if exists "word_entry readable by everyone" on public.word_entry;
create policy "word_entry readable by everyone"
  on public.word_entry for select using (true);

drop policy if exists "word_entry insertable by authed" on public.word_entry;
create policy "word_entry insertable by authed"
  on public.word_entry for insert to authenticated with check (true);
