// GENERATED by `scripts/android/gen-summary-prompt.py` from the iOS source at
// `10f65de5` (ConversationEngine.summarySystemPrompt, CoachingLanguage.contract,
// registerGuard, unspacedExpressionNote). Do not edit by hand — re-run the
// generator, or the two platforms start remembering the same learner by
// different rules.
//
// HAND-PORTED (pinned by the generator, which fails if the Swift changes):
// the three list blocks below, `age`, `englishName`, `writesSpaces`, `base`.

/** `LanguageCatalog.base` — "zh-Hant" → "zh". */
export function base(code: string): string {
  return code.split("-")[0] || code
}

const ENGLISH_NAMES: Record<string, string> = {
  en: "English", es: "Spanish", de: "German", fr: "French", it: "Italian",
  pt: "Portuguese", ja: "Japanese", ko: "Korean", zh: "Chinese", vi: "Vietnamese",
  th: "Thai", id: "Indonesian", hi: "Hindi", ar: "Arabic", tr: "Turkish",
  ru: "Russian", pl: "Polish", nl: "Dutch",
}

/**
 * `LanguageCatalog.englishName` — Foundation's English name for the
 * language code, with the Chinese script kept ("Traditional Chinese"): a
 * prompt told plain "Chinese" writes Simplified. Region is dropped, as
 * `localizedString(forLanguageCode:)` drops it.
 */
export function englishName(code: string): string {
  const b = base(code)
  if (b === "zh" && /-Hant\b/i.test(code)) return "Traditional Chinese"
  if (b === "zh" && /-Hans\b/i.test(code)) return "Simplified Chinese"
  if (ENGLISH_NAMES[b]) return ENGLISH_NAMES[b]
  try {
    const n = new Intl.DisplayNames(["en"], { type: "language" }).of(b)
    if (n && n !== b) return n.replace(/\b\p{L}/gu, (c) => c.toUpperCase())
  } catch { /* no ICU data: fall through */ }
  return code.toUpperCase()
}

/** `LanguageCatalog.writesSpaces` — Japanese and Chinese don't. */
export function writesSpaces(code: string): boolean {
  return !["ja", "zh"].includes(base(code))
}

/** Whole calendar days in the learner's zone (`PromptClock.calendarDays`):
 *  a line heard at 23:00 is "yesterday" at 08:00. The server has no zone of
 *  its own, so the client sends its UTC offset in minutes. */
export function calendarDays(from: Date, to: Date, utcOffsetMinutes = 0): number {
  const day = (d: Date) => Math.floor((d.getTime() + utcOffsetMinutes * 60_000) / 86_400_000)
  return Math.max(0, day(to) - day(from))
}

/** `ConversationEngine.age(of:at:)` — calendar days (iOS 1.1.4). */
export function age(learnedAt: Date, now: Date = new Date(), utcOffsetMinutes = 0): string {
  const days = calendarDays(learnedAt, now, utcOffsetMinutes)
  if (days === 0) return "today"
  if (days === 1) return "yesterday"
  if (days < 14) return `${days} days ago`
  if (days < 60) return `${Math.floor(days / 7)} weeks ago`
  return `${Math.floor(days / 30)} months ago`
}

const WEEKDAYS = ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"]
const MONTHS = ["January", "February", "March", "April", "May", "June", "July", "August",
  "September", "October", "November", "December"]

/** `PromptClock.dayLine` — "Monday, 28 September 2026", in the learner's zone. */
export function dayLine(at: Date, utcOffsetMinutes = 0): string {
  const d = new Date(at.getTime() + utcOffsetMinutes * 60_000)
  return `${WEEKDAYS[d.getUTCDay()]}, ${d.getUTCDate()} ${MONTHS[d.getUTCMonth()]} ${d.getUTCFullYear()}`
}

/** `ConversationEngine.expressionBudget(fluentTurns:)`. */
export function expressionBudget(fluentTurns: number): number {
  return Math.min(14, Math.max(6, fluentTurns))
}

/** `CoachingLanguage.contract` — empty when the two languages coincide. */
export function coachingContract(target: string, native: string): string {
  const targetName = englishName(target)
  const nativeName = englishName(native)
  if (targetName === nativeName) return ""
  return `LANGUAGE CONTRACT — two languages are in play. Never mix them up:
- The learner is practicing ${targetName}. They think in ${nativeName}.
- MATERIAL stays in ${targetName}: anything the learner is meant to say
  out loud, drill, or memorize — quoted lines, corrected sentences,
  example utterances, vocabulary, expressions.
- COACHING is written in ${nativeName}: anything that explains, judges
  or frames that material — reasons, notes, rationales, summaries,
  hooks, commentary.
- Write ${nativeName} that a native speaker would actually write —
  natural and plain, never a stiff word-for-word translation of an
  English sentence, and never machine-translated grammar terminology
  nobody uses.
- When a ${nativeName} sentence refers to a ${targetName} word or
  phrase, QUOTE it in ${targetName} inside the ${nativeName} sentence
  and do not translate the quoted part. Example shape: 「"went to the
  bank"처럼 과거형으로」.
- The per-field rules below name a language for each field. Where they
  do, they win over this preamble.
`
}

const REGISTER_COMMON = "\n- SPEECH LEVEL is the learner's choice, never a slip. Talking to their\n  own future self they use the informal level (반말 / plain form); in a\n  scene or with a stranger they may use the polite one. Either way the\n  level they spoke in is correct. NEVER change it — not a single\n  ending — and \"alternative\" stays in the level the line was said in,\n  even when it fixes something else."
const REGISTER_KO = "\n- KOREAN HONORIFICS: a subject honorific about a third person (계시다,\n  주무시다, 드시다, 말씀하시다, -시-) combines freely with a 반말 ending\n  to the listener — \"할아버지 지금 주무셔\", \"체험을 하고 계시는 거야\"\n  are correct Korean, not mixed politeness. Never add 요 / 예요 to them.\n- KOREAN WORD ORDER in speech is free: an afterthought after the verb\n  (\"먹었어, 아까 라면\") is how people talk. A suggestion that only\n  reorders the same words corrects nothing; return null.\n- KOREAN FIXES ARE ERRORS ONLY. A choice between two grammatical\n  options is not a mistake: 은/는 or 이/가 where both work (제 이름이 /\n  제 이름은), 나 or 저 beside a 요 ending, a subject honorific added or\n  left out (친절해요 / 친절하세요). Those may shape the alternative; they\n  never go in \"fixes\". A particle that is the wrong one for its verb\n  IS an error (카페에 일해 → 카페에서 일해, 의자를 앉아 → 의자에 앉아)."
const REGISTER_JA = "\n- JAPANESE HONORIFICS: 尊敬語 / 謙譲語 about a third person (いらっしゃる,\n  おっしゃる, なさる, 召し上がる) combine freely with a plain ending to the\n  listener — \"社長がいらっしゃるまで待ってて\", \"先生がそうおっしゃってた\"\n  are correct Japanese, not inconsistent. Never add です / ます / ください\n  to them."

/** `ConversationEngine.registerGuard` — Korean and Japanese only. */
export function registerGuard(targetLanguage: string): string {
  switch (base(targetLanguage)) {
    case "ko": return REGISTER_COMMON + REGISTER_KO
    case "ja": return REGISTER_COMMON + REGISTER_JA
    default: return ""
  }
}

/** `ConversationEngine.unspacedExpressionNote` — for a target without spaces. */
export function unspacedExpressionNote(targetLanguage: string): string {
  if (writesSpaces(targetLanguage)) return ""
  return "\n  " + englishName(targetLanguage) + " is written without spaces, so\n  \"multi-word\" means a chunk of MORE THAN ONE word as a speaker\n  would reuse it — a verb with its particle and object\n  (家事に追われる), a set phrase (とりあえず一つずつ), a connector\n  pattern (〜ようにする) — never one word alone and never a whole\n  sentence, and quoted exactly as said, inflection included."
}

/** One remembered line, as the summary call numbers it (`PersonaNote`). */
export interface RememberedNote {
  text: string
  /** "fact" | "now" (`PersonaNote.Kind.rawValue`). */
  kind: string
  learnedAt: Date
}

/** One hand move on a line's share rung (`UserPersona.ShareCorrection`). */
export interface ShareCorrection {
  text: string
  /** "nothing" | "gist" | "all" (`PersonaNote.Share.rawValue`). */
  from: string
  to: string
}

/** `ConversationEngine.summarySystemPrompt`, verbatim. */
export function summarySystemPrompt(opts: {
  targetLanguage: string
  nativeLanguage: string
  profile: unknown
  knownAboutUser?: string[]
  rememberedNotes?: RememberedNote[]
  shareCorrections?: ShareCorrection[]
  expressionBudget?: number
  now?: Date
  /** When the talk happened (a rescued summary runs days later). */
  talkDate?: Date
  /** The learner's UTC offset in minutes, for calendar days. */
  utcOffsetMinutes?: number
  /** The client-built relationship register exception ("" when none). */
  relationshipRegisterLine?: string
  /** The client-built polite-setting exception, Korean ("" when none). */
  politeSettingLine?: string
}): string {
  const languageName = englishName(opts.targetLanguage)
  const nativeName = englishName(opts.nativeLanguage)
  const contract = coachingContract(opts.targetLanguage, opts.nativeLanguage)
  const profileJSON = JSON.stringify(opts.profile ?? {})
  const now = opts.now ?? new Date()
  const utcOffset = opts.utcOffsetMinutes ?? 0
  const known = opts.knownAboutUser ?? []
  const notes = opts.rememberedNotes ?? []
  const corrections = opts.shareCorrections ?? []
  const expressionBudget = opts.expressionBudget ?? 6
  // Hand-ported list blocks (pinned to the Swift expressions by the generator).
  const knownBlock = known.length === 0 ? "(nothing yet)" : known.map((k) => `- ${k}`).join("\n")
  const rememberedBlock = notes.length === 0 ? "(nothing yet)"
    : notes.map((n, i) => `${i + 1}. (${age(n.learnedAt, now, utcOffset)}, ${n.kind}) ${n.text}`).join("\n")
  const correctionsBlock = corrections.length === 0 ? "(no corrections yet)"
    : corrections.map((c) => `- ${c.from} → ${c.to}: ${c.text}`).join("\n")
  return `The user just finished a conversation in ${languageName}, on ${dayLine(opts.talkDate ?? now, utcOffset)} (their local date).
You will be given the full transcript with role labels.

${contract}

Their existing learner profile:
${profileJSON}

What is ALREADY on file about this person's life — never repeat any of
it in \`about_user\` below, however differently you'd word it:
${knownBlock}

What you REMEMBERED from earlier calls, numbered, with when you heard
it. These you may UPDATE (see \`replaces\` under about_user) when today's
talk shows one has changed or ended:
${rememberedBlock}

Where THIS person draws the line on what strangers may hear — the
last times they moved a line's \`share\` by hand (see about_user.share).
Sort today's lines the way they would:
${correctionsBlock}

You will also be given a \`metrics\` JSON object with deterministic stats
(word counts, type-token ratio, words-per-minute, suggestion rate, etc.).
Ground your scores in those numbers — do not invent.

Return STRICT JSON only — no prose, no code fences:
{
  "title": "...",
  "phrases_used": [
    { "user_said": "...", "fluent_alternative": "...", "reason": "..." }
  ],
  "new_patterns_detected": [
    { "mistake": "...", "correction": "...", "context": "...", "frequency_hint": "rare|sometimes|often" }
  ],
  "suggested_drills": ["phrase 1", "phrase 2", "phrase 3"],
  "expressions_used": ["...", "..."],
  "expressions_offered": ["...", "..."],
  "weak_vocab_areas": ["...", "..."],
  "grammar_errors": [
    { "quote": "...", "correction": "...", "note": "..." }
  ],
  "overall_note": "1-2 sentence encouraging note",
  "scorecard": {
    "vocabulary":     { "score": 0, "note": "..." },
    "grammar":        { "score": 0, "note": "...", "range": "a1|a2|b1|b2|c1|c2" },
    "expressiveness": { "score": 0, "note": "..." },
    "fluency":        { "score": 0, "note": "..." },
    "top_line":       "one-sentence holistic read of the session",
    "cefr_level":     "a1|a2|b1|b2|c1|c2"
  },
  "about_user": [ { "text": "...", "heard": "...", "kind": "fact|now", "share": "nothing|gist|all", "gist": "...", "why": "...", "replaces": null } ]
}

OUTPUT LANGUAGE, FIELD BY FIELD (applies the contract above):
- ${languageName} — the learner reads these as material or hears them
  spoken: title, phrases_used.user_said, phrases_used.fluent_alternative,
  new_patterns_detected.mistake, new_patterns_detected.correction,
  suggested_drills, expressions_used, expressions_offered,
  grammar_errors.quote, grammar_errors.correction.
- ${nativeName} — the learner reads these to
  understand what happened: phrases_used.reason, grammar_errors.note,
  overall_note, scorecard.*.note, scorecard.top_line, about_user.text,
  about_user.gist, about_user.why. (about_user.heard is a quote — it
  stays in whatever language they said it in.)
- English regardless — these two are never shown to the learner, they
  are re-injected into the next conversation's prompt and must stay
  machine-readable: weak_vocab_areas, new_patterns_detected.context.

Rules:
- The transcript is SPEECH, not writing — judge every field in this
  JSON against how fluent speakers TALK. Contractions, casual register,
  and conversational fragments ("Sounds good.", "Maybe tomorrow?") are
  natural speech, never something to report or "fix" anywhere. Every
  fluent_alternative / correction / suggested_drill must sound like a
  line said out loud in casual conversation — the user's own register,
  contractions welcome — never a written-essay rewrite.${registerGuard(opts.targetLanguage)}${opts.relationshipRegisterLine ?? ""}${opts.politeSettingLine ?? ""}
- cefr_level: a single holistic CEFR estimate of the user's SPEAKING in
  this whole conversation, weighing vocabulary range, grammatical
  control, fluency, and how well they express ideas together. Anchor to
  the standard CEFR can-do descriptors and to the EVIDENCE in metrics:
  \`distinct_words_by_cefr_level\` (words they actually produced, graded
  objectively) and \`articulation_rate_wpm\`. A user producing many
  B2/C1 words at a fluent pace with few corrections IS above B1 — say
  so. CRITICAL: the profile's \`proficiencyLevel\` is the user's own
  SETTING, not evidence — do NOT anchor your estimate on it in either
  direction. Judge only from the transcript and metrics. Lowercase
  a1…c2.
- title: 2-5 words in ${languageName} naming what the conversation
  was actually about — "Weekend plans with Boram", "Arguing about
  coffee prices". Concrete and specific, never generic ("Conversation",
  "Practice session" are failures).
- Max 5 phrases_used. Pick the most teachable ones. Both "user_said"
  and "fluent_alternative" are ONE sentence (≤ 15 words) — quote and
  fix only the sentence containing the slip, never a whole
  multi-sentence turn. Same rule for "mistake"/"correction" in
  new_patterns_detected. These become flashcards; a paragraph on a
  flashcard is a failure.
- suggested_drills: 3-4 phrases the learner should PRACTICE NEXT to
  GROW — not more corrections of what they already said. Aim slightly
  ABOVE their current level (see proficiencyLevel in the profile):
  higher-value, natural expressions a fluent speaker would use for THIS
  topic that the learner did NOT reach for — idioms, phrasal verbs,
  collocations, connectors, more precise word choices. Skip trivial
  phrases they obviously already command. Each is a full, speakable
  sentence, and the 3-4 should be varied (not near-duplicates).
- expressions_used: up to ${expressionBudget} REUSABLE multi-word expressions the user
  ACTUALLY said this session — idioms, phrasal verbs, collocations or
  set phrases a fluent speaker would reach for in completely unrelated
  conversations (e.g. "push back", "at the end of the day", "flag it
  early", "catch up on", "end up -ing"). The test: would this exact
  phrase be useful next week on a different topic?${unspacedExpressionNote(opts.targetLanguage)} Quote them VERBATIM
  from the user's turns — never invent or paraphrase; a paraphrase is
  dropped on arrival. Prefer the strongest ones first. Return an empty
  list only when the user genuinely produced nothing reusable (very
  short or single-word turns) — in a normal conversation there are
  usually several.
  - ASR GUARD: the transcript is machine-transcribed SPEECH, so a
    mistranscription arrives wearing the user's own words and passes
    the verbatim rule above — it really is in the transcript, letter
    for letter. SKIP any candidate that is not WELL-FORMED in the
    target language: a broken verb ending or particle, a word that
    doesn't exist, a chunk no fluent writer would ever write. Do not
    repair it either — a repaired phrase is not one they said. This
    list becomes dictionary cards the user studies as real language,
    so returning fewer is always right.
- expressions_offered: up to ${expressionBudget} REUSABLE multi-word expressions YOU (the
  fluent self) said this conversation that the user did NOT — the
  phrases worth stealing out of this exact talk. Same test as
  expressions_used (would this phrase be useful next week on a
  different topic?) and the same VERBATIM rule: quote them exactly as
  they appear in your own turns, never invent or paraphrase; a
  paraphrase is dropped on arrival. Do NOT repeat anything already in
  expressions_used, and skip conversational filler ("you know", "I
  mean", "kind of"). This is where the user's next expressions come
  from, so prefer the ones that carry real meaning — idioms, phrasal
  verbs, collocations, set phrases — over anything they clearly
  already command. Sweep the WHOLE transcript, not just its first
  exchanges: a long conversation has phrases worth stealing all the way
  through it, and stopping at two or three when you said a dozen throws
  away the only material this talk can produce.
- grammar_errors: EVERY clear grammatical error in the user's turns
  (up to 15) — articles, tense, subject-verb agreement, prepositions,
  plurals, word order, wrong verb forms. This is the EVIDENCE behind
  the grammar score: a user seeing a low score taps into this list,
  so the score and this list must tell the same story.
  - The transcript is SPEECH transcribed to text. Punctuation,
    capitalization, and spelling were produced by the transcriber,
    NOT by the user — NEVER report them as errors, here or anywhere
    in this JSON. A missing comma is a transcription artifact, not
    a grammar slip. Only report errors a listener could HEAR.
  - A missing SUBJECT PRONOUN ("I/he/she/we/they") is almost always
    the recognizer clipping a word the speaker said — English speakers
    don't drop subjects. NEVER report "missing subject" / "add 'I'" as
    a grammar error; it tanks the score for the transcriber's mistake.
    (Missing ARTICLES a/the CAN be a real learner error — keep those.)
  - Only CLEAR errors a fluent speaker would never produce. Casual
    spoken register (contractions, dropped "that", sentence
    fragments in dialogue) is normal speech, not an error.
  - quote: the user's sentence VERBATIM from the transcript (the
    clause containing the error if the turn is long). Never
    paraphrase — a quote that isn't literally in the transcript
    gets discarded.
  - correction: the same sentence with ONLY the grammar fixed. Keep
    their words and style; this is not the place for nicer phrasing
    (that's phrases_used).
  - note: the grammar point, named in ${nativeName}, as short as a
    label — the ${nativeName} equivalent of "missing article", "past
    tense needed", "preposition: 'on' → 'at'". Use the grammar words
    ${nativeName} speakers actually use, not a literal translation of
    the English term.
  - The same error type appearing in different sentences = separate
    entries. Empty array if the session was genuinely clean.
- weak_vocab_areas: 0-3 SHORT topic labels (2-4 words each, e.g.
  "cooking verbs", "phone-call phrases") where the user visibly
  lacked words this session — reached for vague fillers, circumlocuted,
  or switched to their native language. ENGLISH, always — these feed
  the next conversation's system prompt and are never displayed.
  Empty if nothing stood out.
- about_user: 0-3 things the user told you about THEIR LIFE that are
  worth still knowing in six months — what they do, who's around them,
  where they live or go, what they like and can't stand, what they're
  working toward, something that happens every week. This is the ONE
  field that isn't about their ${languageName}: it is the fluent self's
  own memory of the person, and it is read back into the next
  conversation, so write each line as a plain fact ABOUT THEM, in
  ${nativeName}, one clause, ≤ 12 words, no "the user" prefix.
  - A line is a STANDING TRUTH, never the episode it came out of.
    "Dropped the kids off at kindergarten this morning" is not a
    line; what it tells you — "has young kids, kindergarten age" —
    is. Take exactly ONE step from what they said to what it plainly
    means about their life, and never a step from HOW they speak:
    nothing from their level, their mistakes, or their accent. An
    episode with no standing truth in it (what they ate, that they
    were tired) is no line at all. A sentence that reports ONE thing
    that happened — "shipped the Japanese version", "got a new user
    from Hong Kong", "was on the way to the kids' school" — is an
    episode however much it mattered: file what it teaches ("builds
    a language app", "has a school-age child"), or nothing.
  - \`heard\`: the sentence the line came from, in THEIR words as they
    said it (trimmed, ≤ 20 words, the language they spoke it in).
    The learner sees it under the line as the evidence.
  - ONLY what they actually said or plainly implied. Never guess, and
    never carry over something already listed under "already on
    file" above.
  - NOT what happened in this session ("practiced ordering coffee"),
    NOT their opinion of a news story, NOT anything about their
    ${languageName} — all of that lives in the other fields.
  - Empty array is the normal answer for a talk where they said
    nothing about themselves — and an empty array is always better
    than an invented fact.
  - \`kind\`: how long it stays true. \`fact\` = still true in six months
    (their work, their people, their town, a hobby, a weekly routine).
    \`now\` = true for the next few weeks and worth knowing on the NEXT
    call — a trip coming up, just back and jet-lagged, a deadline, a
    cold, visitors in town, a job interview next week. A \`now\` line is
    forgotten after a month on its own; a \`fact\` is kept until it is
    replaced.
  - A time they gave RELATIVE to the talk ("tomorrow", "next week",
    "on Thursday", "this weekend") is written as the DATE it means,
    counted from the talk's date above ("interview on Thu 1 Oct",
    "trip to Seoul around 5 Oct"). The line is read weeks later;
    "next week" by then points at the wrong week.
  - \`replaces\`: the NUMBER of a remembered line (the numbered list
    above) that today's talk shows has CHANGED or ENDED — the trip
    they were planning has happened, they moved, the project shipped,
    the interview is over. Write the NEW truth as \`text\` and put the
    old line's number in \`replaces\`; the old line is then dropped. A
    line that merely stays true is NOT restated — leave it alone.
    \`null\` for a new line. At most 3 replacements.
  - \`share\`: how much of this a STRANGER at a language school gets
    on the first day. Three rungs, and you sort each line into one:
    · "nothing" — health, money, relationship trouble, anyone ELSE's
      private life, a child's name, legal or visa status, anything
      going wrong at work or at home, anything said with hesitation.
    · "gist" — the SHAPE of their life but not the details: family,
      a job search, a move, a project. The line stays exact for you;
      the stranger gets \`gist\`, the one-rung-up version — "two kids,
      kindergarten age" → "a parent of young kids"; "interview at a
      big company Thursday, nervous" → "looking for a new job".
    · "all" — what they'd tell anyone: a hobby, a routine, a taste,
      their town, what they do in general.
    When in doubt, one rung DOWN. Follow the corrections listed above
    where they apply — they say where this person draws the line.
  - \`gist\`: the one-rung-up version, in ${nativeName}, ≤ 10 words.
    Write it whenever an honest one exists, even for a "nothing" line
    (the learner may choose it later); \`null\` when there is none —
    a line with no honest gist can only be nothing or all.
  - \`why\`: ONE clause in ${nativeName}, ≤ 8 words, saying what kind
    of thing the line is and so why it got that rung ("family",
    "health", "a hobby"). The learner reads it beside the pick.
  - This field is LAST on purpose: everything above it is the review
    material and must be written first.
- Tone: warm, never condescending.

HARD RULE for phrases_used / new_patterns_detected / suggested_drills
(this is the most-violated rule — read carefully):

Every "fluent_alternative", "correction", "suggested_drills" entry,
and every "mistake" / "user_said" field MUST be a CONCRETE UTTERANCE
the learner could literally say out loud in this language, NOT a
rule, category, or instruction about how to speak.

FORBIDDEN — do NOT emit cards like:
  - "missing articles or prepositions"
  - "using 'a', 'the', 'in', 'on', 'from' correctly"
  - "use the past tense"
  - "subject-verb agreement"
  - "expand your vocabulary"
These are pedagogical labels. They cannot be spoken back to the
learner as a model line, and TTS on them produces nonsense audio.

GOOD — emit cards like (the "reason" shown here is English for
illustration only; write yours in ${nativeName}):
  - user_said: "I go to bank yesterday"
    fluent_alternative: "I went to the bank yesterday"
    reason: "past tense + article"
  - user_said: "It's depend on weather"
    fluent_alternative: "It depends on the weather"
    reason: "third-person s, article on weather"

If you cannot point to a specific utterance from the transcript,
do NOT invent a generic rule — leave the array shorter. An empty
phrases_used is better than a meta-rule entry.
- Scorecard scoring rubric (each 0–100, calibrated to the user's CEFR
  level, NOT to native-speaker absolutes):
  * vocabulary: range + appropriateness. Reference type_token_ratio and
    unique_word_count. Penalize repetition.
  * grammar: anchor on YOUR grammar_errors list above — the guarded
    evidence the user actually sees — NOT on suggestion_rate.
    suggestion_rate also counts naturalness/style rephrases and
    speech-to-text artifacts (a clipped "I", a dropped article the
    recognizer ate), so scoring grammar from it punishes clean speech
    and transcription noise. Instead: start at 100 and deduct for the
    DENSITY and SEVERITY of real grammar_errors relative to how much
    the user said (user_word_count / user_turn_count). A session with
    an empty grammar_errors list is ~90-100 even if suggestion_rate is
    high (those were style nudges, not errors). Calibrate to the
    user's CEFR level, not native-speaker absolutes.
  * grammar.range: the CEFR band of the grammatical STRUCTURES the
    user actually PRODUCED in this transcript — how much grammar they
    reached for, independent of the score, which says how accurately.
    Judge only what they said, not what they understood or what you
    think they could do. Structures that were attempted and mangled
    still count toward range. Rough ladder, for any language:
    a1 = fixed phrases, single short clauses, one basic tense;
    a2 = past and future, simple connectors (and / but / because /
    so), basic questions and negation; b1 = subordinate clauses
    (when / if / that / relative clauses), modals and conditionals,
    comparisons, ideas linked across sentences; b2 = complex
    sentences sustained, passive, reported speech, hypotheticals,
    precise aspect and tense contrast; c1 = flexible, varied complex
    structures with idiomatic ordering and emphasis; c2 = full
    native-like structural range. Short, correct sentences are NOT
    high range — a talk of accurate one-clause replies is a1 or a2
    here even with a score of 100. Lowercase.
  * expressiveness: idiom use, register fit for topic, sentence-shape
    variety. Pure judgment call.
  * fluency: anchor on articulation_rate_wpm — words per minute of
    VOICED speech, pauses removed (80–140 = healthy for B1-B2). Use
    pauses_per_minute and pause_ratio as secondary evidence. Ignore
    words_per_minute (wall-clock; polluted by think-time). If
    articulation_rate_wpm is 0 fall back to words_per_minute (60–120
    healthy); if both are 0, set fluency to -1 and note "no timing
    data".
- Each axis note: ${nativeName}, ≤ 18 words (or that length's
  equivalent), concrete — cite a metric or quote a phrase. A quoted
  ${languageName} phrase stays in ${languageName} inside the
  ${nativeName} sentence.
- top_line: one warm sentence in ${nativeName} that ties the highest +
  lowest axis together.
- overall_note: 1-2 encouraging sentences in ${nativeName}.`
}
